### ISSUE TITLE
Error on create Direct HDD Zfs

### ISSUE THREAD

**Issue by cyberax64** [openzfsonwindows/ZFSin#102]
C:\Windows\system32>wmic diskdrive list brief
Caption                    DeviceID            Model                      Partitions  Size
Samsung SSD 970 EVO 250GB  \\.\PHYSICALDRIVE2  Samsung SSD 970 EVO 250GB  1           250056737280
Samsung SSD 850 EVO 120GB  \\.\PHYSICALDRIVE0  Samsung SSD 850 EVO 120GB  0           120031511040
HGST HTS721010A9E630       \\.\PHYSICALDRIVE1  HGST HTS721010A9E630       0           1000202273280

C:\Windows\system32>zpool create tank \\.\PHYSICALDRIVE0
DeviceName said OK with '*'
DriveGeometry said OK
LayoutInfo said OK
DiskExtents said NG
cannot create 'tank': invalid argument for this pool operation

C:\Windows\system32>

**Comment by jheuking** [comment]
you could try `zpool create tank PHYSICALDRIVE0`

**Comment by cyberax64** [comment]
:O ok thanx :)

**Comment by jheuking** [comment]
Guessing from #103, i assume that this is fixed :)
