### ISSUE TITLE
New problem on ZFS Encrypted

### ISSUE THREAD

**Issue by cyberax64** [openzfsonwindows/ZFSin#103]
- zpool create -O encryption=on -O keyformat=passphrase SSD PHYSICALDRIVE0 <= OK
- zpool export SSD <= OK

- reboot this computer <= OK

- zpool import SSD <= OK
- zfs load-key SSD <= ERROR blue screen and correct or error password :(

**Comment by jheuking** [comment]
I guess the encryption stuff is still untouched on windows, you just entered uncharted territory :)
I'm not sure, what is planned there.

**Comment by cyberax64** [comment]
lol ok

**Comment by lundman** [comment]
Does it crash if you `zpool import -l` instead?

**Comment by cyberax64** [comment]
I just did the test at the moment, and the pc crashed

**Comment by cyberax64** [comment]
tested on windows 10 64bit build 1809 / 17763.316

**Comment by lundman** [comment]
rats ok - the windows port is about a year behind in commits compared to osx, and I know there are encryption fixes in osx. You'll have to wait until they come in for encryption (or cherry-pick them in yourself), we were focussed on getting the Windows base to run well first.   And encryption still needs code to handle password input better.

**Comment by cyberax64** [comment]
ok I thank you for this port of ZFS on windows, I discovered on linux and he brought me the 3 things I wanted to have. raid management, compression management and hard disk encryption. thank you for your work :)

**Comment by cyberax64** [comment]
I download visual studio and the SDK to see if I find a solution :)

**Comment by lundman** [comment]
Actually there was only a few related to crypto - I'll check if it helps

**Comment by lundman** [comment]
Ok with b4fb8c8187b8a244c29866c168a9f2b5e3832eb5 I can import again but ran into the bug where we don't release a drive letter. But should work if imported after a reboot

**Comment by cyberax64** [comment]
I finished installing visual studio 2017 and the SDK ... and I managed to compile ZFSin but zfsinstaller refuses to install the new driver error start service

**Comment by lundman** [comment]
zfsinstaller install .\ZFSin.inf
 
from Administrator CMDline

**Comment by cyberax64** [comment]
yes that's what I did.

**Comment by cyberax64** [comment]
good it does not crash anymore. but it does not load the encryption key

zpool create -O compression=gzip-9 -O encryption=on -O keyformat=passphrase SSD PHYSICALDRIVE0 <= OK

zpool export SSD <= OK

zpool import -l SSD <= "
...
Enter passphrase for 'SSD': win_isatty: return 1
1 / 1 keys successfully loaded
"

zfs mount SSD <= ERROR clé not found. return: "cannot mount 'SSD': encryption key not loaded"

**Comment by lundman** [comment]
hmm ok clearly needs me to look at it properly.. i seem to remember this bug on osx, so I'll have a look at the commits

**Comment by lundman** [comment]
OK, turns out it was badly defined ioctls, so a handful of commands did not work.

https://github.com/openzfsonwindows/ZFSin/commit/76918eab1097a076fd808cd57fc314b743aa4a39

**Comment by cyberax64** [comment]
yessssssssssss is working !!!! :p you have perfect ! thanx you :)
