### ISSUE TITLE
windows server 2019 datacenter

### ISSUE THREAD

**Issue by valador** [openzfsonwindows/ZFSin#104]
Hello, this driver work only in unsigned drivers mode? if i boot in standart mode - i have error:
`Unable to open \\.\ZFS: No error.`
In disabled driver signature checks mode i install ZFSin, create pool:
`zpool create -O casesensitivity=insensitive -O compression=lz4 -O atime=off -o ashift=12 tank \\.\PHYSICALDRIVE1`
have error (in latest debug and i try pre-latest release - no changes):
`cannot create 'tank': invalid argument for this pool operation`
But pool is created(magic?) I try `zpool import` and i have error like:
```
 pool: tank
     id: 9360454818919078037
  state: UNAVAIL
status: The pool can only be accessed in read-only mode on this system. It
        cannot be accessed in read-write mode because it uses the following
        feature(s) not supported on this system:
        org.zfsonlinux:userobj_accounting
action: The pool cannot be imported in read-write mode. Import the pool with
        "-o readonly=on", access the pool on a system that supports the
        required feature(s), or recreate the pool from backup.
 config:

        tank                   UNAVAIL  unsupported feature(s)
          /dev/physicaldrive1  ONLINE
```
I try created pool from ubuntu livecd:
`zpool create -O casesensitivity=insensitive -O compression=lz4 -O atime=off -o ashift=12 tank /dev/sdb`
and pool create and mount without error. I try import this created pool from windows and i have similar error (org.zfsonlinux:userobj_accounting).
Any ideas?

**Comment by lundman** [comment]
`Unable to open \\.\ZFS: No error.`

Yeah the kernel part is not loaded, you will need to enable TestMode, or at least, disable driver signature checks.

But, when you go to create a pool, it actually does that from userland, so that more or less works, but it will not mount, or work or anything, since the kernel component is not there.

**Comment by jheuking** [comment]
...and you need to use `PHYSICALDRIVE1` instead of `\\.\PHYSICALDRIVE1`

**Comment by lundman** [comment]
Oh and lastly if you solve those issues, the `org.zfsonlinux:userobj_accounting` bit at the end is that the pool was created with that feature, which only ZOL understand at the moment.

When you create the pool, use `-d` to stop it from enabling all features, then make sure to enable features that are supported on the platforms you want to use.

**Comment by lundman** [comment]
I downloaded windows server VM and tested the installer works. Open new issues if there are additional problems
