### ISSUE TITLE
Computer reboot does not restore pools

### ISSUE THREAD

**Issue by fire** [openzfsonwindows/ZFSin#117]
Rebooting the computer does not restore pools that were mounted.

**Comment by lundman** [comment]
That is correct, it will most likely be done by a service we install, perhaps in connection to the https://github.com/openzfsonwindows/ZFSin/issues/92 helper program. It will also have to start `zed` - which has also not been ported yet. (on that topic, should we somehow run the bash scripts with zed, or convert them to something Windowsy)

**Comment by fire** [comment]
Wanted to make a bug report so:

* Design can be written
* Tracked
* Commentary can be addeds
* Prioritized

I can almost imagine zfsin as my data drives. Currently using steam on my pools for testing. Steam games can be verified and be disposable.

**Comment by lundman** [comment]
I'm all for that, carry on

**Comment by Wowfunhappy** [comment]
For what it's worth, I currently have task scheduler set up to import my pool on startup.

```
Open Task Scheduler → Action → Create Task:
• General:
	• Name: Mount [pool name]
	• Run with highest privileges: Enabled
• Triggers → New → Begin the task: At log on
• Actions → New
	• Action: Start a program
	• Program/script: zpool
	• Add arguments: import [any additional options you want] [pool name]
```

**Comment by lundman** [comment]
That is quite interesting, I have added it to the wiki.

**Comment by fire** [comment]
This works I'll make a another post for porting zed then.
