### ISSUE TITLE
zpool iostat 5 does not auto-repeat

### ISSUE THREAD

**Issue by fire** [openzfsonwindows/ZFSin#118]
zpool iostat 5 does not auto repeat.

**Comment by lundman** [comment]
688ac6cb9b607534b38ec8321c11b969ae77b91c

**Comment by fire** [comment]
Will wait for the next release or a build to test

**Comment by lundman** [comment]
You can try the AccessDenied test: http://www.lundman.net/OpenZFSOnWindows-debug-20190312.exe

**Comment by fire** [comment]
works.
