### ISSUE TITLE
Import failure with sub-pools

### ISSUE THREAD

**Issue by jaw3000** [openzfsonwindows/ZFSin#119]
I have a pool created using ZFS on Linux (Ubuntu) that I have attempted to import using 'zpool import Storage.' The main pool 'Storage' mounts fine, but the sub-pools (ex. Storage/Archive) refuse to mount. Any files/folders at the root mount directory belonging to the parent pool ('Storage') are mounting fine and usable, and folders are visible for the sub-pools as well, but these folders are empty as the pools are not mounted. I'm not sure if there is a problem with child pools mounting under a parent pool, and I would need to change the mount point for these sub-pools? If there is some other issue going on? I have no problem mounting these on Linux or MacOS.

C:\WINDOWS\system32>zpool import Storage
cannot mount '/Storage/Archive1': mount failed
cannot mount '/Storage/Archive2': mount failed
cannot mount '/Storage/Archive3': mount failed
cannot mount '/Storage/Archive4': mount failed
cannot mount '/Storage/Archive 5': mount failed
cannot mount '/Storage/Backup': mount failed

C:\WINDOWS\system32>zfs get mounted
NAME              PROPERTY  VALUE    SOURCE
Storage           mounted   yes      -
Storage/Archive1     mounted   no       -
Storage/Archive2    mounted   no       -
Storage/Archive3     mounted   no       -
Storage/Archive4    mounted   no       -
Storage/Archive5  mounted   no       -
Storage/Backup	mounted   no       -

C:\WINDOWS\system32>zpool status
  pool: Storage
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
        still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
        the pool may no longer be accessible by software that does not support
        the features. See zpool-features(5) for details.
  scan: scrub repaired 0 in 0 days 15:36:50 with 0 errors on Sun Oct 14 16:00:53 2018
config:

        NAME                     STATE     READ WRITE CKSUM
        Storage                  ONLINE       0     0     0
          raidz1-0               ONLINE       0     0     0
            /dev/physicaldrive1  ONLINE       0     0     0
            /dev/physicaldrive4  ONLINE       0     0     0
            /dev/physicaldrive0  ONLINE       0     0     0

errors: No known data errors

C:\WINDOWS\system32>zpool list
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
Storage  5.44T  5.35T  89.4G        -         -    54%    98%  1.00x  ONLINE  -

C:\WINDOWS\system32>zfs list
NAME               USED  AVAIL  REFER  MOUNTPOINT
Storage           3.56T      0  66.9G  /Storage
Storage/Archive1      105G      0   105G  /Storage/Archive1
Storage/Archive2    1.67T      0  1.67T  /Storage/Archive2
Storage/Archive3      157G      0   157G  /Storage/Archive3
Storage/Archive4     910G      0   910G  /Storage/Archive4
Storage/Archive5   197G      0   197G  /Storage/Archive5
Storage/Backup   500G      0   500G  /Storage/Backup

**Comment by lundman** [comment]
`zfs mount` will also show the mountpoints for everything.

In this case, the pool and its dataset gets mounted fine as it is assigned to a driveletter, but perhaps we broke the "mount ZFS inside ZFS" code recently, as all your lower datasets are not mounting.

You could, as a test, set a lower dataset driveletter and export/import to confirm that works.

https://openzfsonosx.org/wiki/Windows_driveletter#Windows_Drive_letters

**Comment by jheuking** [comment]
i recently did a commit to make zfs mount fail more gracefully. So I added a few more checks to make it return a failure instead of crashing or breaking anything.
This one is it: https://github.com/openzfsonwindows/ZFSin/commit/2c0b86f0790a427a56129728ed28dbdfdc045ca1
But i think, i wasn't able to mount inside zfs as well, when i did that commit.
Mounting to a driveletter should work though.

**Comment by jaw3000** [comment]
Ok, this is what is happening. It appears the code to mount a pool inside another pool is indeed broken. I assigned a drive letter to one of the five lower pools and it mounted fine, but the ones without a drive letter refused to mount at all. Any idea if/when this can get fixed?

Also, how does assigning a drive letter to a lower pool on Win affect mounting on Linux? Will the lower pool no longer mount within the main pool? Is there a way to temporarily (one-time) mount a lower pool to a drive letter under windows to get around this error, without changing the ZFS mount settings?

**Comment by lundman** [comment]
Here's one of those fun things where the same version of Windows behaves differently. I have no issues with tank on E: and tank/lower on E:\lower. I'll have to try something differently and see if I can trigger the problem.

**Comment by lundman** [comment]
There have been many import/mount fixes. Closing old ticket, please reopen if there still are issues.
