### ISSUE TITLE
zfs send doesn't seem to work with -R

### ISSUE THREAD

**Issue by ShaRose** [openzfsonwindows/ZFSin#120]
As the title says, it doesn't seem like zfs send works with replication works.

Specifically, it seems that adding -R (replication streams) returns an empty stream, although it seems to return proper information for dry runs.

Steps to verify:

A new pool was created using `zpool.exe create -O casesensitivity=insensitive -O compression=lz4 -O atime=off -o ashift=12 tank PHYSICALDRIVE1`

A new filesystem was created using `zfs create tank/a`

Some snapshots were created of this new filesystem: `zfs snap tank/a@test1` and `zfs snap tank/a@test2`

Now, using normal zfs send:

`zfs send tank/a@test1 | zfs recv -Fu tank/b` This works.

`zfs send -i tank/a@test1 tank/a@test2 | zfs recv -Fu tank/b` This also works.

Now, attempting replication:

`zfs send -R tank/a@test1 | zfs recv -Fu tank/c` "Cannot receive: failed to read from stream"

`zfs send -Ri tank/a@test1 tank/a@test2 | zfs recv -Fu tank/c`  "Cannot receive: failed to read from stream"

using zstreamdump (or simply piping the result to a file), you can see it is outputting nothing at all, which results in a 0 length stream.

Interestingly, adding -nP properly prints out sane estimations of how much space would be used for normal and incremental send jobs.

**Comment by lundman** [comment]
There is 25f8a67d26a6662727cd8bbd3304cfa52089d173 which starts to address the issues with send -R, but I believe there are still bits in recv missing. I think @jheuking is still on the case though, so most likely there are more fixes to come.

**Comment by ShaRose** [comment]
That would explain it. At least there's an issue created for it at the moment.

**Comment by jheuking** [comment]
Currently a bit busy with other things, but I try to look at that, when I got time!
I already tried zfs send like this `zfs send -R tank@backup > zbackup.bin` which seemed to work.
But it looks like there is still something wrong with receive, but had no time to look at that yet.
So yeah...  I wouldn't be offended if anyone else wants to look at that in the meantime. :)

**Comment by lundman** [comment]
1e0978c3f51fe08a9fbc8659185bfd79444ad00d
http://www.lundman.net/OpenZFSOnWindows-debug-20190328.exe
