### ISSUE TITLE
Cannot import zpool from FreeNAS disk

### ISSUE THREAD

**Issue by blockofdynamite** [openzfsonwindows/ZFSin#121]
I'm trying to mount this zpool on Windows 10 and for some reason it's just not seeing the pool on my drive. This is the relevant output from "zpool import" and it says there are no pools available for import. I'm not seeing "zfs" in any kind of partition label or anything, and I can't seem to force zfs on windows to import this disk.

path '\\\\?\scsi#disk&ven_&prod_st32000644ns#5&1673cb0&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' and '\\\\?\PhysicalDrive0'
read partitions ok 2
    gpt 0: type d56fd960 off 0x10000 len 0x80000000
    gpt 1: type d56fd960 off 0x80010000 len 0x1d141100000

**Comment by lundman** [comment]
I believe we expect the partition to be named "zfs" and it is somewhat optional when coming from bsd variants. We should probably relax this requirement.

**Comment by blockofdynamite** [comment]
That makes sense, and thanks for the quick reply! Do you know of a safe way to relabel the partition as "zfs" within Windows, or should that be done on a linux machine? I tried to use zfsonlinux first, but it's currently incompatible with the kernel I use. I was surprised at how easy ZFSin was to set up.

**Comment by lundman** [comment]
You would need to correct this line:

https://github.com/openzfsonwindows/ZFSin/blob/master/ZFSin/zfs/lib/libzfs/libzfs_import.c#L2176

I believe someone else came across this and simply set the partition name to "zfs", but I am unsure what tool they used to do so. If you don't build the code yourself, ask for a test build here.

**Comment by blockofdynamite** [comment]
Aha, I got it. I booted up a live linux distro and used zfsonlinux to rename the zpool and also used gnome-disk-utility to rename the partition. I'm not sure which one did the trick, but I can now successfully import it into Windows! Your tool is awesome!

**Comment by lundman** [comment]
9f0ff1a4c6ddd2133fd44659ff8659e3e98b52f9
http://www.lundman.net/OpenZFSOnWindows-debug-20190328.exe
