### ISSUE TITLE
On Windows reboot zfs driver will not be initialized

### ISSUE THREAD

**Issue by fire** [openzfsonwindows/ZFSin#124]
```
>zpool list
Unable to open \\.\ZFS: No error.
Failed to initialize the libzfs library.
```

Not sure how to debug this.

**Comment by qinq-net** [comment]
It's because the ZFS driver is not correctly installed. See the `Installing a binary release section` in README.md.
Maybe you need to disable Secure Boot. The driver is signed but not compatible with Secure Boot. I have tried to sign the cert with by own KEK key, but not helpful. When I disable Secure Boot, the driver loads successfully.

**Comment by lundman** [comment]
It is possible there is a flag set somewhere (inf file?) that specifies when it should be loaded, and perhaps we have it set to "boot time" which we can not do if secureboot is enabled. Possibly this flag should be the next one along from "boot time" - whatever that may be.

**Comment by fire** [comment]
I don't think I have secure boot. Anything I can provide?

**Comment by lundman** [comment]
Rebooting is not an issue in the VMs here. 

```
0x00000000 | SERVICE_BOOT_START
0x00000001 | SERVICE_SYSTEM_START
0x00000002 | SERVICE_AUTO_START
0x00000003 | SERVICE_DEMAND_START
0x00000004 | SERVICE_DISABLED

If your driver's start type is SERVICE_BOOT_START ... the binary image file of a boot-start driver must contain an embedded signature.
```

So that should not be the problem here, as we are SERVICE_SYSTEM_START.

**Comment by fire** [comment]
Problems were because of unsigned drivers. Newest test fixed it.

**Comment by lundman** [comment]
Looks like i told Inno Setup to copy the wrong files over, the inf2cat.exe stamping puts the files in a lower directory, x64/Debug/ZFSin/* which should be signed for installer.
