### ISSUE TITLE
Entering an incorrect passphrase causes BSOD

### ISSUE THREAD

**Issue by zfs2019** [openzfsonwindows/ZFSin#125]
Importing a pool with `-l` and if the passphrase is wrong, the system will crash.
```
# zpool import -l pool1
```

**Comment by lundman** [comment]
https://github.com/zfsonlinux/zfs/issues/8604

**Comment by zfs2019** [comment]
With [0.18](https://github.com/openzfsonwindows/ZFSin/tree/0.18), importing a pool with a wrong passphrase doesn't crash the system anymore.
