### ISSUE TITLE
Rebooting causes hostid to change

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/ZFSin#126]
I forget what the hostid is currently based on, but it should remain same over reboots on the same machine, so we should change this code and base it on something a little more stable.

**Comment by fire** [comment]
Can you prioritize this so that I don't have to import -f?

**Comment by lundman** [comment]
a9a3396

**Comment by fire** [comment]
On reboot hostid is zero? Or maybe I need to reboot another time since it's a new driver install.

**Comment by lundman** [comment]
Hmm so it seems, that Registry is not available at boot

**Comment by lundman** [comment]
Hah ok, totally forgot about userland, the hostid3 installer might do the deed

**Comment by lundman** [comment]
hostid is now set in registry.
