### ISSUE TITLE
Alternative streams trash files.

### ISSUE THREAD

**Issue by fire** [openzfsonwindows/ZFSin#130]
Workaround
```
   - Open run command
    - Type gpedit.msc then enter
    - Open User Configuration>Administratives Templates>Windows Components>Attachement Manager.
    - Double-click on "Do not preserve zone information in file attachement" and set it to enabled, then press ok
```

**Comment by fire** [comment]
> Actually, Windows doesn’t have any tools to deal with the alternative data streams. For instance, if you have to delete them from a number of files at once, you’d better use a third-party console tool by Mark Rusinovich — streams.

> For example, to recursively delete the alternative streams of all executable files in c:\Download\, run this command:

> c:\TOOLS\streams.exe -s -d c:\Download\*.exe

http://woshub.com/how-windows-determines-that-the-file-has-been-downloaded-from-the-internet/

**Comment by fire** [comment]
I forgot to give a proper description:

ZFSin replaces each file with a 1KB file.

```
[ZoneTransfer]
ZoneId=3
``

**Comment by lundman** [comment]
Can you give notes on what you do, and how it fails?

**Comment by fire** [comment]
Save a file from Firefox to a ntfs drive. Copy it to the zfs drive. Notice the file is trashed with the above contents.

**Comment by lundman** [comment]
Thanks - I'll take a look in the office in the morning

**Comment by fire** [comment]
Note that this means any file download from the internet saved to ntfs and then moved/copied to zfs is trashed. Regardless of time between saving and moving.

**Comment by lundman** [comment]
Yeah, most likely any file with streams - downloaded or not. I think I have a good guess, but need to find time to load up the debugger

**Comment by lundman** [comment]
Ok, So it seems that it will call MJ_CREATE with an "empty" filename, containing only a stream name:

`struct _UNICODE_STRING ":Zone.Identifier:$DATA"`

However, `FileObject->RelatedFileObject` is set to the source file in question.

ZFSin needs to handle this case

**Comment by lundman** [comment]
743e85e

**Comment by fire** [comment]
Tell me when there's a release.

**Comment by lundman** [comment]
I often knock out nightly for small fixes https://openzfsonosx.org/wiki/Windows_builds

**Comment by fire** [comment]
Appears to be resolved.
