### ISSUE TITLE
"Attempted Switch from DPC" BSOD, when downloading files using Chrome

### ISSUE THREAD

**Issue by vmlemon** [openzfsonwindows/ZFSin#136]
Recently, using the 20190423 build, under Windows 10 Build 16299.rs3_release.170928-1534, I started to receive BSODs, with the the aforementioned stop code, when trying to download files, using Google Chrome 73.0.3683.86 (even opening the "Save As" directory selection dialogue can trigger it), onto a ZFS dataset/volume.

I also receive the same crash, when trying to uninstall Magix Music Maker (which requires a case-insensitive file system, due to its main executable loading DLLs, using differing cases to the "real" values on disk), from a ZFS dataset.

Attaching MiniDumps, from the last two crashes. 

[MagixChrome.zip](https://github.com/openzfsonwindows/ZFSin/files/3148696/MagixChrome.zip)

**Comment by lundman** [comment]
If you are able, use WinDbg to get the stack https://openzfsonosx.org/wiki/Windows_BSOD
or I'll get around to it at some point

**Comment by lundman** [comment]
Seems to be connected to
```
zfs_vnop_lookup: denied due to SeAccessCheck()
```

**Comment by vmlemon** [comment]
Not sure if it's the same issue, but with a brand-new pool, created under Ubuntu, on a spare 128GB MicroSD card, I receive a SYSTEM_SERVICE_EXCEPTION BSOD, when trying to download a file, using Chrome 74.0.3729.169, on the same build of Windows, using OpenZFS 20190603.

I'm still trying to get a MiniDump, for that scenario...

**Comment by vmlemon** [comment]
It took at least 3 attempts, to get this dump, but I can reliably reproduce the SYSTEM_SERVICE_EXCEPTION BSOD, merely by starting to download any file from https://wireshark.org/download/automated/win64/, waiting a few seconds, whilst the "Save As..." dialogue is visible, navigating to the root of the dataset, and then hitting "Save".

[060519-24593-01.zip](https://github.com/openzfsonwindows/ZFSin/files/3257034/060519-24593-01.zip)

If it makes a difference, the Ubuntu pool was created with ` zpool create -d -O compress=on -O dedup=on -O casesensitivity=mixed Winux128 /dev/sdc`.

**Comment by vmlemon** [comment]
When things crash, I do get left with an incomplete download file (e.g. `Unconfirmed 990785.crdownload`), so Chrome is at least requesting to write things to disk...

**Comment by lundman** [comment]
It would be helpful if you could paste stacks from the minidumps - at least, faster for me :) 

Your last minidump dies:

```
 ffffe786`122bc33c : nt!MmCheckCachedPageStates+0x13a
 ffffc108`00000000 : nt!CcMapAndCopyInToCache+0x5e8
 00000000`00000002 : nt!CcCopyWriteEx+0x10b
 ffff8580`c61fd150 : ZFSin!fs_write+0x60b [c:\src\zfsin\zfsin\zfs\module\zfs\zfs_vnops_windows.c @ 4682] 
```

So the cache code is not quite right it seems

**Comment by vmlemon** [comment]
No worries - it looks like they let you download just the Windows SDK, and Debugging Tools, without fighting with the rest of Visual Studio (which I haven't been able to install, on this crappy, underpowered machine), so it'd just be a case of setting up the debugger, with the symbol server settings, and probably pointing it to the OpenZFS PDBs, and hoping that everything works... :)

I suspect that I might just wipe it, and try upgrading it to a newer version of Windows 10, from DVD, or see if I can get it to install on my Mac, under VirtualBox, without throwing random localisation file errors, during personalisation, like it did, last time.

**Comment by lundman** [comment]
I think you can just get windbg.exe - no reason to install all of Visual Studio - 

I'm working on updating the wiki with instructions

**Comment by lundman** [comment]
Ok, wiki updated, https://openzfsonosx.org/wiki/Windows_BSOD#WinDbg.exe_in_the_GUI

added screengrabs as I went through your minidump.  and it does seem that you have to get the SDK to get the windbg.exe - I suppose I'm probably not allowed to make just the exe available either.

Also, you don't have to run windbg.exe on the machine that crashes (I run it on my Win10 VM on OSX after all)

**Comment by vmlemon** [comment]
Not sure if it's just a one-hit wonder, but I was able to use the build 20190606, with the infernal MicroSD card, to download a random file (an older OpenZFS build installer), without any crashes, and open it, to the point where I receive a prompt to install it. 

I suspect that it'd probably work fine, on my HDD, until Google find another way of doing streaming writes that breaks things...

**Comment by vmlemon** [comment]
Still, I'm sure that I'll probably discover some other way of breaking things, in the name of trying to make a more reliable product (ZFS on optical media, maybe?)... :)

**Comment by vmlemon** [comment]
Interesting, so I can download, and save a ZIP archive, to the root of the dataset, without problems - but, when I go to extract its contents, WinRAR complains about it being corrupted, at 67% extraction:

<code>
! D:\takeout-20190530T131009Z-001 (1).zip: Checksum error in D:\takeout-20190530T131009Z-001 (1)\Takeout\Location History\Location History.json. The file is corrupt
</code><br/>

The apparent size for the file is the same (31.6 MB (33,142,820 bytes)), if I save it on either NTFS, or ZFS, at least, but if I save the archive on NTFS, and unpack it onto ZFS, the process is supposedly successful. The problem doesn't seem to be in the extraction process, itself, since if I move the archive from NTFS, onto ZFS, and unpack it on ZFS, the process works fine...

*Shrugs*

**Comment by lundman** [comment]
Ok, I'll give winrar tomorrow - today I only looked at cached writes - could be a bug in cached reads

**Comment by vmlemon** [comment]
No worries - thanks for looking into this hairy mess! 

I wonder how much of it is intrinsic to the storage media, itself, exposing new issues in OpenZFS, where they wouldn't surface, on magnetic media, and how much of it is issues that someone would get, eventually, on a HDD of the "right" flavour, eventually, anyway?

**Comment by vmlemon** [comment]
(When I first started testing OpenZFS-on-Windows, I was reluctant to report issues, since it seemed that quite a few of them "went away", when I changed HDD models/media - but, in hindsight, I'm sure that others might have encountered them, with the same drives, and sworn off of further testing)

**Comment by lundman** [comment]
I think it is more likely that it writes "simpler" to removable storage, which is why you came across the cache problem - also we did only just enable it.

**Comment by vmlemon** [comment]
Makes sense - after all, I don't think that SMB testing (which is how I first noticed the caching issues) was at the top of anyone's list, since if you want file-sharing on ZFS, you usually go to FreeBSD, or Solaris/IllumOS, or at a push, Linux. :)

**Comment by lundman** [comment]
or NFS!

**Comment by vmlemon** [comment]
True. 

In fairness, I've learnt quite a lot about how Windows works, just by testing this project - since most of the Windows development that I've done, has all been userspace code (written using C++/Qt), or stuff targeting embedded systems/smartphones, and most of the fun, systems stuff, or small toys, I end up building under Linux/UNIX, since the toolchains are less hassle to configure, and use. 

It would be nice, if I can get to a stage where I can start scratching itches, eventually - although, I admit, I haven't coded, for quite a long time, since my current day job isn't massively technical, and I only get to play with this stuff, to stop my skills from rusting, occasionally.

**Comment by vmlemon** [comment]
Interesting. 

So, I picked up a brand-new, 4TB Toshiba Canvio HDD, this morning, created a pool under Ubuntu (I've got an old-ish version, installed on a BTRFS partition, on a USB Flash drive; and, used <code>zpool create -d -O compress=on -O dedup=on -O casesensitivity=mixed Canvio /dev/sdd</code>, without any other options, other than having SELinux enabled, with a <code>.autorelabel</code> file, to force the creation of SELinux xattrs), moved over the contents of my home directory, and rebooted into Windows 10 (without exporting the ZPool, in advance, and doing an "zpool import -af"), and managed to download a ZIP using Chrome, and unpack it using WinRAR, with no BSODs, and no corruption.

Annoyingly, I now can't import my 2TB HDD, without receiving a BSOD, for which I'm struggling to obtain a MiniDump, though. :(

Bizarrely, the download writing process feels faster, with the new caching patches, but it doesn't explain why we get the corruption, on MicroSD, but not on a factory-fresh magnetic disk...

**Comment by vmlemon** [comment]
Managed to get an IRQL_NOT_LESS_OR_EQUAL BSOD, today, when trying to run the Debugging Tools for Windows installer, somewhat ironically, after I used the new drive under Mac OS X, yesterday...

[060819-19875-01.zip](https://github.com/openzfsonwindows/ZFSin/files/3268369/060819-19875-01.zip)

**Comment by vmlemon** [comment]
With OpenZFS 20190612, Windows 10 Build 1903, and Chrome 75.0.3770.100, downloading files onto a ZFS dataset seems to work fine (tested on MicroSD), no matter how long I open the "Save As..." dialogue open for, and the files seem to be downloaded intact, at least with no third-party AV installed.

Haven't tested unpacking files with WinRAR, with this combination of software builds.

**Comment by vmlemon** [comment]
Meh, so I had a more detailed follow-up prepared, before my Windows installation ate itself, again - but since last time, I tested with WinRAR (installed on the MicroSD-based dataset), and a bunch of large downloads (ranging up to ~2GB), in .TAR.GZ, and .ZIP format, and unpacking everything seemed to work fine, without any problems; and, doing a bunch of mixed-sized downloads, in Chrome seem to work fine, now, so I'm happy to close this, for the time being.
