### ISSUE TITLE
"process_has_locked_pages" BSOD on zpool import

### ISSUE THREAD

**Issue by jheuking** [openzfsonwindows/ZFSin#137]
Happens with Vaettfang, when doing `zpool import -N -f zroot` of a FreeBSD created pool with a SanDisk USB3.0 Cfast card reader...
Have to find out, if i have some kernel dumps flying around... unfortunately this is the laptop I use for development, so it's a little bit harder to live debug this issue...

**Comment by lundman** [comment]
Make sure you try the latest nightly too (or just master)

**Comment by jheuking** [comment]
na, have to enter test mode for that...guess i should set up a machine for testing again

**Comment by lundman** [comment]
latest nightly is installer like releases - just dont want to make a github release for each one :)

**Comment by jheuking** [comment]
ah, okay, that would be interesting
where can i get them?

**Comment by lundman** [comment]
https://openzfsonosx.org/wiki/Windows_builds

**Comment by jheuking** [comment]
woah, it worked!

**Comment by jheuking** [comment]
ok, guess I can close this then, gr8 :) 👍
