### ISSUE TITLE
"APC_INDEX_MISMATCH" BSOD, when KasperSky AntiVirus is installed

### ISSUE THREAD

**Issue by vmlemon** [openzfsonwindows/ZFSin#139]
Using Windows 10 Build 16299.rs3_release.170928-1534, OpenZFS 0.19, and KasperSky Free 19.0.0.1088 (e).

When the aforementioned AV software is installed, and an attempt is made to perform a scan, on either pool dataset mount time (if realtime protection is enabled), or on individual files, from Windows Explorer's shell menu, I can reliably produce an APC_INDEX_MISMATCH BSOD. 

Annoyingly, I can't always obtain a MiniDump, although I'm attaching the last one that I was able to generate.

[053119-14093-01.zip](https://github.com/openzfsonwindows/ZFSin/files/3239168/053119-14093-01.zip)

**Comment by lundman** [comment]
The first thing to trigger here is:

```
*** Assertion failed: address != NULL
***   Source File: c:\src\zfsin\zfsin\zfs\module\zfs\zfs_vnops_windows.c, line 4519

in `fs_read()` - debugging as to why you'd want to call read with no buffer.

**Comment by vmlemon** [comment]
Unsure as to why, but after rebooting from that attempt, attempting to reimport my pool under Windows stalls at:

```
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
device '#1048576#272629760#\\?\sd#disk&sandisk&df4032&0.1#5&21d48ba8&0&f7d9a904&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#1048576#272629760#\\?\sd#disk&sandisk&df4032&0.1#5&21d48ba8&0&f7d9a904&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#21685600256#1978678640640#\\?\usbstor#disk&ven_wd&prod_elements_25a3&rev_1019#574343344e364c4e4b4c4655&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#21685600256#1978678640640#\\?\usbstor#disk&ven_wd&prod_elements_25a3&rev_1019#574343344e364c4e4b4c4655&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#273678336#16777216#\\?\sd#disk&sandisk&df4032&0.1#5&21d48ba8&0&f7d9a904&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#20480#209715200#\\?\usbstor#disk&ven_wd&prod_elements_25a3&rev_1019#574343344e364c4e4b4c4655&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
zpool_open_func_win: enter
device '#290455552#29928456192#\\?\sd#disk&sandisk&df4032&0.1#5&21d48ba8&0&f7d9a904&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#290455552#29928456192#\\?\sd#disk&sandisk&df4032&0.1#5&21d48ba8&0&f7d9a904&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
device '#20480#209715200#\\?\usbstor#disk&ven_wd&prod_elements_25a3&rev_1019#574343344e364c4e4b4c4655&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}' filetype 1 0x3
setting path here '/dev/physicaldrive1'
setting physpath here '#21685600256#1978678640640#\\?\usbstor#disk&ven_wd&prod_elements_25a3&rev_1019#574343344e364c4e4b4c4655&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
```
If I remember correctly, I was able to recover from the last time that it happened, by mounting it under Mac OS X, and letting it do the automatic scrub/repair, but I haven't got time to do that, again, tonight...

**Comment by lundman** [comment]
OK I see it - there is a third way to pass buffer in

**Comment by lundman** [comment]
Ok, I could do selective, and full, scans with this b302699

**Comment by vmlemon** [comment]
Cool. Please can I get a build, so that I can beat on it, later?

**Comment by lundman** [comment]
Yep, build is in the nightlybuilds page on wiki

**Comment by vmlemon** [comment]
Thanks for the quick fix, and the new build! 

After waiting a little while, I was able to import my pool, past the stall point, and managed to scan a single file, without any crashes, as well as begin scanning 12000+ files, in the dataset pertaining to my FreeBSD home directory, with realtime protection disabled.

**Comment by vmlemon** [comment]
I did manage to get a BSOD, when trying to download a file using Chrome, after switching realtime protection back on, but I think the core issue for on-demand scans is pretty much fixed, for now.

[053119-14390-01.zip](https://github.com/openzfsonwindows/ZFSin/files/3241044/053119-14390-01.zip)

**Comment by lundman** [comment]
ok, so turn on real-time protection, then download from chrome to ZFS drive? I will try

**Comment by lundman** [comment]
Closing for stale, maybe fixed, sort of thing..
