### ISSUE TITLE
[FR] Add link to test builds in readme

### ISSUE THREAD

**Issue by yurikoles** [openzfsonwindows/ZFSin#142]
I mean this link, It's hard to find it in Google, at least for me.
https://openzfsonosx.org/wiki/Windows_builds

**Comment by zfs2019** [comment]
5c1aceb11bb49a134589b2d4b4757e2bd91a8b4e
Updating README on every build is tedious, so I added the link to the wiki.

**Comment by yurikoles** [comment]
@zfs2019,

I meant just that link, thanks!

**Comment by yurikoles** [comment]
@zfs2019,

You had forget to add: `Closes #142` to commit message.

**Comment by zfs2019** [comment]
@yurikoles Sorry, please close this.

**Comment by yurikoles** [comment]
Fixed by 5c1aceb11bb49a134589b2d4b4757e2bd91a8b4e
