### ISSUE TITLE
[Feature Request] Tunable for IO cachemgr

### ISSUE THREAD

**Issue by zfs2019** [openzfsonwindows/ZFSin#146]
The commit 46492aaddab95dfa7cdebec1a9e2c7afcddba7b2 added IO cachemgr support.

It works, but there are problems:

1. There is ARC (and L2ARC if any), so there can be multiple copies of the same data. That is redundant and inefficient.
2. Incurs additional CPU load. (To copy data to ARC and Standby memory.)
3. Can be a performance bottleneck. (I don't know why, but it slows down file read if the cache is full.)

If you open Task Manager and monitor resources when reading large files, you know what I mean.
I reverted that commit and tested with IO cachemgr disabled, it worked flawlessly.
But it is required by SMB, right?
So what about the tunable parameter to disable that cache?

**Comment by lundman** [comment]
There does seem to be more interaction with CcMgr than SMB, so there will most likely be more things to be discovered - but running without it is certainly much simpler code. I have no objection to a tunable to control CcMgr usage.

**Comment by zfs2019** [comment]
2804c241387c0771b5b2e60453a4e239df6e71ee
I confirmed that `zfs_disable_wincache` works as expected in the registry and `kstat`. Thank you!
