### ISSUE TITLE
Only able to  import ZFS Pool that was created using ZFS on Linux as read only

### ISSUE THREAD

**Issue by INaCloud** [openzfsonwindows/ZFSin#154]
Decided to make my machine windows because Linux Mint was too buggy. After installing ZFS on Windows I tried to import my ZFS Pool and got this message.

This pool uses the following feature(s) not supported by this system:
        org.zfsonlinux:userobj_accounting
All unsupported features are only required for writing to the pool.
The pool can be imported using '-o readonly=on'.
cannot import 'zfs-san': unsupported version or feature

I used the basic command zpool import -f zfs-san. Am I going to have to create a virtual machine with Linux on it and import the zfs pool and turn off that feature to get it to import into windows? Is there something that can be done without having to do that. Plus I don't even know if that would be the solution.

[Full ZFS Import Output.txt](https://github.com/openzfsonwindows/ZFSin/files/3427142/Full.ZFS.Import.Output.txt)

**Comment by lundman** [comment]
Unfortunately, Linux is the only OS with `org.zfsonlinux:userobj_accounting` at the moment, You will have to create a pool without this feature (and the project quota one as well). You can create a new pool and zfs send from the readonly pool, if you have a secondary device to use temporarily.

**Comment by INaCloud** [comment]
Thank you. I guess I will have to run  linux vm as a temporary san and share with nfs.

**Comment by INaCloud** [comment]
Thank you. I will create a linux vm and import it there. I will just use the vm as a temporary san
