### ISSUE TITLE
Memory leak / kernel exception

### ISSUE THREAD

**Issue by misterfinster** [openzfsonwindows/ZFSin#157]
I believe I have found a possible leak in the driver.   

 My testing scenario / environment is:
* windows 10 pro 1903 build 18362.267
* ZFSin (http://www.lundman.net/OpenZFSOnWindows-release-20190612.exe) (AdvanceOnly fix).
* raidz2 pool (6 drives, 1 cache, 1 log)
* system is 2 x Xeon v3 w/ 256GB ECC ram
* write caching is enabled on all drives in the pool (but not disabled write-flush)
* testing with only 1 dataset (the primary one that is created upon initialisation)

[081019-54359-01.dmp.zip](https://github.com/openzfsonwindows/ZFSin/files/3489614/081019-54359-01.dmp.zip)

It takes a while, perhaps a day or so, but the available memory goes to zero and then the kernel panic occurs.

call stack from the dump:
```
ZFSin!kmem_error(int error = 0n5, struct kmem_cache * cparg = 0xffff8e82`b722c048, void * bufarg = 0xffff8e9b`c57e3000)+0x210
ZFSin!kmem_slab_free(struct kmem_cache * cp = 0xffff8e82`b722c048, void * buf = 0xffff8e9b`c57e3000)+0x90
ZFSin!kmem_magazine_destroy(struct kmem_cache * cp = 0xffff8e82`b722c048, struct kmem_magazine * mp = 0xffff8e9b`0da7a6d0, int nrounds = <Value unavailable error>)+0xdb
ZFSin!kmem_depot_ws_reap(struct kmem_cache * cp = 0xffff8e82`b722c048)+0x61
ZFSin!kmem_cache_reap(struct kmem_cache * cp = 0xffff8e82`b722c048)+0x6c
ZFSin!taskq_thread(void * arg = 0xffff8e82`b73276c8)+0x1db
nt!PspSystemThreadStartup+0x55
nt!KiStartSystemThread+0x2a
```

**Comment by lundman** [comment]
Neat - thanks for reporting it. `kmem_error()` will dump text to the internal log, so next step is to check what those messages are ( [Wiki](https://openzfsonosx.org/wiki/Windows_BSOD#Windows_Crash_Dumps) ) alas, work is closed for the week, so it will take me a while to get there.

**Comment by misterfinster** [comment]
Trying to produce the cbuf I get this:
```
3: kd> dt ZFSin!cbuf
???? 
Memory read error fffff8017a854000
```

I'm assuming it's related to the mini dump.  I can try kernel memory but if that includes committing all the 'leaked' memory, it will be quite the load.

**Comment by lundman** [comment]
WinDbg to read in the minidump should let you look up cbuf - but if it doesn't work, it doesn't work :)

All pages is not needed, minidump is usually enough.

**Comment by misterfinster** [comment]
I've been running the latest nightly 20190712 with no issue yet.  I will re-open with at least a valid crash dump if I can manage to see it again.  Thanks and keep up the good work.  Hope I can contribute further.
