### ISSUE TITLE
[FR] Add appveyor CI

### ISSUE THREAD

**Issue by yurikoles** [openzfsonwindows/ZFSin#160]
Hi @lundman,

What do you think about CI, which will also to download artifacts, e.g. nightlies for commits?

**Comment by yurikoles** [comment]
I'm volunteering to implement it, if it's something that can be eventually merged.

**Comment by lundman** [comment]
I have no idea what CI or appveyor are :) Please give more details

**Comment by yurikoles** [comment]
CI stands for continuous Integration, it builds code and also runs tests, if they are present. For every commit/PR. So we can easily catch regressions.

**Comment by lundman** [comment]
Ah yes, ZOL has that which is very neat. It has always been something that would be nice to have but I've never had time to set anything up, and nobody else has been around. :)

**Comment by yurikoles** [comment]
Oh, I see that GitHub actions support Windows, so let's try them first.

I suppose that this feature will be considered if I do send a PR?

**Comment by lundman** [comment]
Yep, definitely - if it would help, you can have elevated access to the github project. Let me know what is required.

**Comment by yurikoles** [comment]
What about some basic sanity checks? Do we have some? I'm not sure that we'll have admin privileges on runner VM, but let's add it either way, so they may at least would available for local run.

**Comment by yurikoles** [comment]
I don't need admin access to your project, GH just picks special file if it finds it. But in any case I will try in my fork first :)

**Comment by lundman** [comment]
Technically, OpenZFS itself uses "cstyle.pl" for basic sanity checks, but I've been a bit lax in this area. I should go over the project and make sure we at least adhere to that coding standard. ZOL does have a bunch of checks setup correctly

**Comment by yurikoles** [comment]
@lundman please take a look at https://ci.appveyor.com/project/yurikoles/zfsin/builds/26940658

It seems that you need to add me as collaborator here and grant access to AppVeyor

**Comment by lundman** [comment]
The log output is showing it is not getting the INLCUDE directories from the project. All those header files are in spl and zfs include directory.

**Comment by yurikoles** [comment]
I see similar errors when I build from CLI.

**Comment by TheCakeIsNaOH** [comment]
@lundman pretty sure that this can be closed

**Comment by lundman** [comment]
oh yeah, cheers everyone
