### ISSUE TITLE
Installer packaging documentation

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [openzfsonwindows/ZFSin#170]
The current documentation on how to build the inno setup install is somewhat lacking. There are a couple of things I think would be useful to have documented, presumably in the zfsinstaller readme. 

1. Add more explicit instructions on how to build the installer, and add also a command-line build example using `iscc`. 

2.  Where to get the `vcruntime140.dll`, I presume that it is from the version of build tools used to build the binaries, but I am not sure.

3. How to create a testing self-signed certificate to use, or how to disable the signing steps in the build. Either would work, although creating a self-signed certificate is probably the better option.

**Comment by lundman** [comment]
I guess I had in mind that the only person who will be making an Installer bundle would be me ( or whomever is PackageAdmin for the project if I ever get more developers) - so it would not be something regular developers would do.  As a developer, they would presumably be in TestMode (no certificate needed), and use Deploy to run your own builds. (no installer).

But it would not surprise me to find that there could be circumstances where building a local Installer, with own certificate, would be useful - perhaps that is what we are discussing here. So we certainly should add more details to the zfsinstaller and InnoSetup compile script file.

On the topic of `vcruntime140.dll` - I was a bit disappointed to find that the compiled binaries relied on something external, and I have not yet looked into it properly. For now (then), I just copied in the .dll for the installer. I believe it gets installed with the SDK - and I suspect I am supposed to install a SDK_redist when the installer runs. It is on the TODO.

I would not be the right person for the self-signed certificate details. It took me forever to get a real cert and figure out how to sign everything so it would not complain when installing. It feels like a house of cards at the moment, and if I look at it wrong, it'll fall apart :) But eventually I'll learn to trust how it works..   

One could argue that the Installer should also installer the man-pages, but that felt like a "can open, worms everywhere" case too, as I'm unsure how to present that to user, convert manpage to something Windowsy?

**Comment by TheCakeIsNaOH** [comment]
> But it would not surprise me to find that there could be circumstances where building a local Installer, with own certificate, would be useful - perhaps that is what we are discussing here.

Yes, that is what I meant. It would also allow nightly builds more easily.

> For now (then), I just copied in the .dll for the installer. I believe it gets installed with the SDK - and I suspect I am supposed to install a SDK_redist when the installer runs. It is on the TODO.

Alrighty, I'll look into this. Copying the .dll seems to be the most simple, but the redist package is the MS recommended way. Whichever it ends up being, documenting, and scripting it would be good. 

>but that felt like a "can open, worms everywhere"

Yes, agreed.

**Comment by lundman** [comment]
> Yes, that is what I meant. It would also allow nightly builds more easily.
The nightly builds on Windows are the easiest ever. I just hit compile in devstudio, then push Compile in Inno - installer.exe produced. I feel spoiled (compared to the steps on osx).

But I suppose creating automated nightlies could be tempting, if Inno would work from commandline. The only issue is the whole certificate thing i suppose.

**Comment by TheCakeIsNaOH** [comment]
> The only issue is the whole certificate thing i suppose.

So visual studio is automatically test signing the drivers, inno setup is the only sticking point. 

I'll set it so the arguments for signtool are given in the signtool configuration rather then in the script itself. 

Also, on the subject of the vcruntime dlls, the debug dll(`vcruntim140d.dll`) is not supposed to be redistributed. So the debug installer releases are actually breaking MS licensing. 
>https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=vs-2019
You cannot redistribute all of the files that are included in Visual Studio; you are only permitted to redistribute the files that are specified in Redist.txt or the online "REDIST list." Debug versions of applications and the various Visual C++ debug DLLs are not redistributable.

**Comment by TheCakeIsNaOH** [comment]
Well, PR merged and the issues are addressed so this is good to close.
