### ISSUE TITLE
vcruntime140d.dll debug dll not redistributable. 

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [openzfsonwindows/ZFSin#175]
This is only about the debug version of the dll, not the release vcruntime140.dll

From here- https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=vs-2017
>You cannot redistribute all of the files that are included in Visual Studio; you are only permitted to redistribute the files that are specified in Redist.txt or the online "REDIST list." Debug versions of applications and the various Visual C++ debug DLLs are not redistributable.

Additionally, the `vcruntime140d.dll` included in visual studio are under a debug_nonredist folder, which seems to confirm that it should not be redistributed. 

I would recommend taking down all of the `OpenZFSOnWindows-debug.exe` installers released with the dll included, and for future releases only uploading the release installer, or not including the dll in the debug version

Original comment- https://github.com/openzfsonwindows/ZFSin/issues/170#issuecomment-539795071

**Comment by lundman** [comment]
As a test I changed the runtime compile argument to MT/MTd and it no longer requires vcruntime140.dll - at slightly fatter .exe.   For now that is cleaner until the day we want to revisit the idea of making the libraries into .dlls.

I'll get around to removing the debug installers at some point.
