### ISSUE TITLE
BSoD on importing a pool.

### ISSUE THREAD

**Issue by MadHau5** [openzfsonwindows/ZFSin#185]
Microsoft Windows [Version 10.0.18362.418]
ZFSin 0.20 (Forvitnask)

I was going to file a bug report, stating that I was unable to mount datasets with `legacy` mountpoints.
As I wanted to make sure that this was not because of an older version of ZFSin, I uninstalled it (Systkin 0.19) and then installed the new release (Forvitnask 0.20).

After doing so, simply importing the pool (`zpool import tank`) causes a BSoD.
`tank` was created in FreeBSD but was working with ZFSin 0.19 (Systkin).

I did not compile ZFSin.

**Comment by lundman** [comment]
Ah a regression perhaps. There is no "mount_zfs" command just yet, so legacy can't be handled while it is set as legacy. But should be straight forward to fix. The "zfs" command renamed as "mount_zfs" is the path it will take once I have a chance to look at it.

**Comment by MadHau5** [comment]
What about the BSoD on 0.20? My pool fails to import and my EFI is not configured enough (I don't have grub) to boot FreeBSD but some important files are present in the home directory.
By the way, there are multiple datasets (`tank/home` and `tank/fbsd` are the important ones) while `tank` itself contains nothing.

**Comment by lundman** [comment]
Can you provide the crash dump output from BSOD? The are some details here: https://openzfsonosx.org/wiki/Windows_BSOD  or make the minidump available somewhere for me to look at.

**Comment by lundman** [comment]
Actually hmm, your minidumps would probably look like:
```
 : nt!CcGetPartition+0xb8
 : nt!CcWriteBehind+0x2f
 : nt!CcWorkerThread+0x244
 : nt!ExpWorkerThread+0x105
 : nt!PspSystemThreadStartup+0x55 
 : nt!KiStartSystemThread+0x2a
```
Which I can trigger importing something here - I did do some changes to CcMgr, so that tracks. Let's see if I can figure out why it happens

**Comment by MadHau5** [comment]
I just tried out Systkin (0.19), which was working before, and it now also results in a BSoD...
I'll try to get the Forvitnask (0.20) ones in a bit.

**Comment by lundman** [comment]
Ok its wrong, but the hard question is how to know when you can release memory, the lazy-writer keeps kicking in after I do so. Unless someone knows here, I'll have to think on this for bit

**Comment by MadHau5** [comment]
I just reinstalled Windows and got Systkin (0.19), and now it works...

**Comment by lundman** [comment]
It is possible this was related to ea2b1a9 - import with unlinked-drain list entries would crash (and the list can be emptied on a working system import, then be importable again in windows).
