### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by arturkow2000** [openzfsonwindows/ZFSin#188]
ZFSin triggers BSOD on null pointer dereferncne in dmu_read_win_dbuf (null zdb).
Tested on ZFSin Forvitnask.

00 ffff950e 6abb17a8 fffff805 223da9e4 nt!KeBugCheckEx
01 ffff950e 6abb17b0 fffff805`2239c279 nt!PspSystemThreadStartup$filt$0+0x44
02 ffff950e 6abb17f0 fffff805 223c9ecf nt!_C_specific_handler+0xa9
03 ffff950e 6abb1860 fffff805 222c3555 nt!RtlpExecuteHandlerForException+0xf
04 ffff950e 6abb1890 fffff805 222c7aee nt!RtlDispatchException+0x4a5
05 ffff950e 6abb1fe0 fffff805 223d301d nt!KiDispatchException+0x16e
06 ffff950e 6abb2690 fffff805 223cf205 nt!KiExceptionDispatch+0x11d
07 ffff950e 6abb2870 fffff809 75180812 nt!KiPageFault+0x445
08 ffff950e 6abb2a00 fffff809 753325cd ZFSin!dmu_read_win_dbuf+0x42 [c:\src\zfsin\zfsin\zfs\module\zfs\dmu.c @ 1709] 
09 ffff950e 6abb2ab0 fffff809 752f0071 ZFSin!zvol_read_win+0x1bd [c:\src\zfsin\zfsin\zfs\module\zfs\zvol.c @ 2488] 
0a ffff950e 6abb2b30 fffff809 752efe9d ZFSin!wzvol_WkRtn+0x1c1 [c:\src\zfsin\zfsin\zfs\module\zfs\zfs_windows_zvol_scsi.c @ 804] 
0b ffff950e 6abb2bc0 fffff805 22267ddf ZFSin!wzvol_GeneralWkRtn+0x6d [c:\src\zfsin\zfsin\zfs\module\zfs\zfs_windows_zvol_scsi.c @ 848] 
0c ffff950e 6abb2c00 fffff805 222bd645 nt!IopProcessWorkItem+0xff
0d ffff950e 6abb2c70 fffff805 2232a715 nt!ExpWorkerThread+0x105
0e ffff950e 6abb2d10 fffff805 223c86ea nt!PspSystemThreadStartup+0x55
0f ffff950e 6abb2d60 00000000 00000000 nt!KiStartSystemThread+0x2a

**Comment by lundman** [comment]
f531ff7
But hmm well, I'm not convinced that is enough.
