### ISSUE TITLE
DATASET: destroying sub-dataset makes directory inaccessible

### ISSUE THREAD

**Issue by inoperable** [openzfsonwindows/ZFSin#193]
How to replicate: 
- Create a dataset, for example named **archive**, `X` is the number of a the the physical disk (device):
`zpool create -f -O casesensitivity=mixed -O compression=lz4 archive PhysicalDiskX`
- Create a subset with zfs command 
`zfs create archive/books`
- Trying to mount this sub-dataset with driveletter won't work

zpool list:
```
C:\>zpool list
NAME      SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
archive   298G   200G  98,5G        -         -     8%    66%  1.00x  ONLINE  -
V:\>zfs list
NAME            USED  AVAIL  REFER  MOUNTPOINT
archive         200G  89,1G   200G  /Volumes/archive
archive/books    24K  89,1G    24K  /Volumes/archive/books
C:\>zfs get driveletter archive
NAME     PROPERTY     VALUE        SOURCE
archive  driveletter  V            local
C:\>v:
V:\>dir
 Volume in drive V is archive
 Volume Serial Number is 1983-1116

 Directory of V:\

22/11/2019  14:55    <DIR>          .
22/11/2019  14:55    <DIR>          ..
23/11/2019  16:44    <JUNCTION>     books [..]
V:\>cd books
The system cannot find the path specified.
```
Explorer says Location is not accessible. The name of the file cannot be resolved by the system.

**Comment by inoperable** [comment]
I think I wrongly set the permissions first since now it works. Need to take a closer look at acl

**Comment by lundman** [comment]
If you change driveletter pro, you have to manually run `zfs umount` and `zfs mount` - it perhaps should do that automatically in the future..
