### ISSUE TITLE
Unable to import anything after 12-Dec build

### ISSUE THREAD

**Issue by despair86** [openzfsonwindows/ZFSin#196]
```
C:\> zpool import -f -o readonly=on [any of my pools]
This pool uses the following feature(s) not supported by this system:
        com.delphix:log_spacemap
        org.zfsonlinux:userobj_accounting
        org.zfsonlinux:project_quota
```
this works for a `data2`, which is a simple RAID1 mirrored vdev, but not for a `data` let alone a Solaris boot `rpool`, both of which are single-device vdevs.

**Comment by lundman** [comment]
OK, so the message there is because those pools have features that the Windows version does not yet support. Those features will come at some point of course, but you'd have to create the pools without those features to be able to import them. (zpool create -d ...)

Just mention panic in the description, do you also experience BSOD?  Also, which version are you running of the Windows port? Ideally you should be running http://www.lundman.net/OpenZFSOnWindows-debug-20191212.exe

**Comment by despair86** [comment]
ohh. Was using the one on GitHub release page. I'll try this one then

**Comment by despair86** [comment]
This actually worked! May want to update the GitHub release page 😅 
Will hold on until the current Solaris feature flags get merged downstream

**Comment by lundman** [comment]
nice - yeah, it is probably due for another release.

**Comment by despair86** [comment]
Reopened as I am unable to open any of my pools even in read-only mode:
```
C:\WINDOWS\system32>zpool status
no pools available

C:\WINDOWS\system32>zpool import -f data2
path '\\?\scsi#disk&ven_hitachi&prod_hua723020ala641#5&1e87ce0f&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive0'
read partitions ok 2
    gpt 0: type c8efd5b0 off 0x20000 len 0x1d1c08f1e00
    gpt 1: type c8efd5b0 off 0x1d1c0911e00 len 0x800000
asking libefi to read label
path '\\?\scsi#disk&ven_hitachi&prod_hua723020ala641#5&1e87ce0f&0&010000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive1'
read partitions ok 2
    gpt 0: type c8efd5b0 off 0x20000 len 0x1d1c08f1e00
    gpt 1: type c8efd5b0 off 0x1d1c0911e00 len 0x800000
asking libefi to read label
path '\\?\scsi#disk&ven_wdc&prod_wd10eads-65m2b0#5&1e87ce0f&0&040000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive2'
read partitions ok 2
    gpt 0: type c8efd5b0 off 0x20000 len 0xe8e0591e00
    gpt 1: type c8efd5b0 off 0xe8e05b1e00 len 0x800000
asking libefi to read label
path '\\?\scsi#disk&ven_adata&prod_su800#5&2e701078&0&020000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive3'
read partitions ok 2
    gpt 0: type c8efd5b0 off 0x20000 len 0x773ba31e00
    gpt 1: type c8efd5b0 off 0x773ba51e00 len 0x800000
asking libefi to read label
path '\\?\scsi#disk&ven_sata&prod_ssd#5&2e701078&0&030000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive4'
read partitions ok 4
    mbr 0: type 7 off 0x100000 len 0x24300000
    mbr 1: type 7 off 0x24400000 len 0x6fa4100000
    mbr 2: type 0 off 0x0 len 0x0
    mbr 3: type 0 off 0x0 len 0x0
asking libefi to read label
Processing volume '\\?\Volume{939546d1-0000-0000-0000-100000000000}'
Processing volume '\\?\Volume{939546d1-0000-0000-0000-402400000000}'
zpool_open_func_win: enter
zpool_open_func_win: enter
cannot import 'data2': no such pool available
```

**Comment by lundman** [comment]
Ah yes, looks like you are right - I don't always update the `zpool.exe` on my test system (always pushed new kernel code, but userland I have to move manually - unless VS can be taught to move other binaries too, that would be neat), and the EFI reading code appears wrong after the wosix work. Any other zpool.exe might just work, but I'll see if I can fix it quickly.

**Comment by lundman** [comment]
Ok it is due to passing `OVERLAPPED` to `WriteFile()` and `ReadFile()`, but leaving it as zero, so all reads and writes happen to offset = 0, not the offset we want. I'll have a fix tomorrow.

**Comment by lundman** [comment]
7f1b384
Should work as expected with 20200115 release.
