### ISSUE TITLE
panic("%s: not initialised", __func__); in cv_timedwait_hires()

### ISSUE THREAD

**Issue by datacore-tlaurent** [openzfsonwindows/ZFSin#212]
At boot time I hit this panic.  
	if (cvp->initialised != CONDVAR_INIT)
		panic("%s: not initialised", __func__);

Quick analysis shows that there's a race condition between the cvp initialization and the start thread using the cvp.  I'm fixing it and will submit the PR.

4: kd> kv
Child-SP          RetAddr           : Args to Child                                                           : Call Site
00 ffffaf00`327a7960 fffff804`a7553ea1 : fffff804`a7a2f060 fffff804`a7a2f0a0 00000000`00989680 00000000`00000000 : ZFSin!cv_timedwait_hires+0x47 [F:\repos\zfsin\ZFSin\spl\module\spl\spl-condvar.c @ 229] 
01 ffffaf00`327a79f0 fffff802`5b23a005 : 00000000`00000000 fffff804`a7552f00 00000000`00000000 00000000`00000000 : ZFSin!spl_free_thread+0xfa1 [F:\repos\zfsin\ZFSin\spl\module\spl\spl-kmem.c @ 4922] 
02 ffffaf00`327a7c10 fffff802`5b378c36 : ffffaf00`31684180 ffff9a85`dc705040 fffff802`5b239fc4 00000000`00000000 : nt!PspSystemThreadStartup+0x41
03 ffffaf00`327a7c60 00000000`00000000 : ffffaf00`327a8000 ffffaf00`327a2000 00000000`00000000 00000000`00000000 : nt!KiStartSystemThread+0x16

clock_t
cv_timedwait_hires(kcondvar_t *cvp, kmutex_t *mp, hrtime_t tim,
                 hrtime_t res, int flag)
{
    int result;
	LARGE_INTEGER timeout;

	if (cvp->initialised != CONDVAR_INIT)
		panic("%s: not initialised", __func__);
	ASSERT(cvp->initialised == CONDVAR_INIT);

4: kd> dt cvp
Local var @ 0xffffaf00327a79f0 Type cv*
0xfffff804`a7a2f060 
   +0x000 kevent           : [2] _KEVENT
   +0x030 waiters_count_lock : 0
   +0x038 waiters_count    : 0
   +0x03c initialised      : 0x12345678

	spl_free_thread_exit = FALSE;
	(void) thread_create(NULL, 0, spl_free_thread, 0, 0, 0, 0, 92);
	(void) cv_init(&spl_free_thread_cv, NULL, CV_DEFAULT, NULL);

**Comment by datacore-tlaurent** [comment]
Fixed with https://github.com/openzfsonwindows/ZFSin/pull/213

**Comment by lundman** [comment]
Also, you are now fixing things in OsX port as well, congratulations :)

https://github.com/openzfsonosx/spl/commit/663b9461c63ee4d14f164adb3fd88bbd5b2da275
