### ISSUE TITLE
Dual Boot Scenario

### ISSUE THREAD

**Issue by shadowrylander** [openzfsonwindows/ZFSin#216]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I'm running this on a dual-booting `Surface Book 2` alongside `Manjaro Kyria`. I was wondering if there would be any problem with force importing my pool between the two systems every time I switched, even multiple times a day, or if doing so would damage the pool, or anything else on the systems, somehow. <br>
&nbsp;&nbsp;&nbsp;&nbsp; Thank you kindly for the help!

**Comment by lundman** [comment]
Nah, force just means you ask it to ignore that the hostID isn't the same as last time. It is meant as a warning to you.

You can in fact set the hostID to be the same too - it is just a made up unique number on Windows, not connected to any hardware;

https://openzfsonosx.org/wiki/Windows_Registry

By setting `\HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\ZFSin\hostid` REG_QWORD value_from_linux

**Comment by shadowrylander** [comment]
Ooh! I'll test it out right after dinner! Thanks!

**Comment by shadowrylander** [comment]
Quick question: is that `REG_QWORD` or `REG_DWORD`?

**Comment by lundman** [comment]
If it is there, use that sorry.  Lookup the hostid on ZOL, I think you use /proc or something for it. It will be a hex value like 0xa568b1ef and put that in Windows reg.

**Comment by shadowrylander** [comment]
Great! Or I could just force it every time, right? A small startup script could take care of that easily enough!

**Comment by GeorgeGhost** [comment]
BTW if creating on Linux use -o feature@project_quota=disabled -o feature@userobj_accounting=disabled to allow rw import on Windows

**Comment by shadowrylander** [comment]
@GeorgeGhost: I used the following, from [here](https://github.com/openzfsonwindows/ZFSin/issues/128#issuecomment-485203360), but they didn't seem to work:
```bash
zpool set feature@async_destroy=enabled pool
zpool set feature@bookmarks=enabled pool
zpool set feature@embedded_data=enabled pool
zpool set feature@empty_bpobj=enabled pool
zpool set feature@enabled_txg=enabled pool
zpool set feature@extensible_dataset=enabled pool
zpool set feature@hole_birth=enabled pool
zpool set feature@spacemap_histogram=enabled pool
zpool set feature@filesystem_limits=enabled pool
zpool set feature@multi_vdev_crash_dump=enabled pool 
zpool set feature@edonr=enabled pool
zpool set feature@lz4_compress=enabled pool
zpool set feature@sha512=enabled pool
zpool set feature@skein=enabled pool
zpool set feature@large_blocks=enabled pool
```

I can try again, though.

**Comment by GeorgeGhost** [comment]
@shadowrylander I haven't tried those, but seemed to be ok to import disabling those two I posted earlier.(needs to be done on pool creation)

**Comment by shadowrylander** [comment]
Got it; I'll try it on the spare Micro SD I have in my Surface.
