### ISSUE TITLE
zpool writes are 20x zvol writes

### ISSUE THREAD

**Issue by imtiazdc** [openzfsonwindows/ZFSin#239]
![image](https://user-images.githubusercontent.com/60249953/78700074-81b20d00-7922-11ea-8554-ee6a26588d32.png)

@lundman after these two changes:
[15e6376](https://github.com/openzfsonwindows/ZFSin/commit/15e6376e87330348c9a8f013e42bbedc949c3a71)
[65faac1](https://github.com/openzfsonwindows/ZFSin/commit/65faac1ab1468a43fea91a1933a4a95c1fc7f094)
the write clogging has reduced to a large extent. However, **I am seeing up to 20x more write activity on zpool compared to zvol**. May be, the issue existed even without the above change.

Is this on expected lines?
What could be leading to this?
What is generally acceptable ratio between zpool writes and zvol writes?

**Below is my setup:**
**VM configuration:**
4 vCPU
8 GB RAM
**zvol settings:**
8GB (thick provisioned)
Everything is default. Dedup=off, Compression=off, ...
**Iometer settings:**
4 workers
Data pattern = full random
No of outstanding IOs = 64
Access spec = 4 KiB; 0% Read; 100% random

Thanks,
Imtiaz

**Comment by lundman** [comment]
Actually, it is quite interesting;

```

# Start with fresh pool, and empty ZVOL 

$ ./zfs list
NAME       USED  AVAIL  REFER  MOUNTPOINT
tank/vol  60.8M  18.9G  60.8M  -

$ ./zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  19.5G  5.93M  19.5G        -         -     0%     0%  29.51x  ONLINE  -

# Write large file, in this case, 500MB

$ ls -lh /f/
-rw-r--r-- 1 WDKRemoteUser 197121 543M Apr  7 17:20  bigfile

# How much space is consumed?

$ ./zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  19.5G  5.46G  14.0G        -         -    10%    27%  1.00x  ONLINE  -

$ ./zfs list
NAME       USED  AVAIL  REFER  MOUNTPOINT
tank/vol  4.43G  14.0G  4.43G  -

```

I'm impressed by that write amplification, we could DDOS with this!

**Comment by lundman** [comment]
So issuing:

```
$ dd if=/dev/urandom of=test bs=4096 count=2
8192 bytes (8.2 kB, 8.0 KiB) copied, 0.0305634 s, 268 kB/s
```
Ie, 2 blocks of 4096 writes.

On a FAT32 zvol:
```
FFFFB706C0313080:zvol_write_iokit(offset 0x408b1000 bytes 0x2000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1644000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1654000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1664000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1674000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1684000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1694000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x16a4000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x16b4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x16c4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x16d4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x16e4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x16f4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1704000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1714000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1724000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1734000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1744000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1754000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1764000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1774000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1784000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1794000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x17a4000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x17b4000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x17c4000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x17d4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x17e4000 bytes 0x10000)
FFFFB706C0313080:zvol_write_iokit(offset 0x17f4000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1804000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1814000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1824000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1834000 bytes 0xf000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1843000 bytes 0x1000)
FFFFB706C0313080:zvol_write_iokit(offset 0x408a2000 bytes 0x1000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1434800 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x143c200 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x1434800 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x143c200 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x1434800 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x1444000 bytes 0x200)
FFFFB706C0317380:zvol_write_iokit(offset 0x143c200 bytes 0x7a00)
FFFFB706C0317380:zvol_write_iokit(offset 0x1434800 bytes 0x7a00)
FFFFB706C0313080:zvol_write_iokit(offset 0x408b2000 bytes 0x1000)
FFFFB706C0313080:zvol_write_iokit(offset 0x1444200 bytes 0x200)
FFFFB706C0317380:zvol_write_iokit(offset 0x143c200 bytes 0x7a00)
FFFFB706C0317380:zvol_write_iokit(offset 0x1434800 bytes 0x7a00)
FFFFB706C0317380:zvol_write_iokit(offset 0x408a2000 bytes 0x1000)
FFFFB706C0317380:zvol_write_iokit(offset 0x1844000 bytes 0x1000)
FFFFB706C0317380:zvol_write_iokit(offset 0x408b5000 bytes 0x10000)
FFFFB706C0317380:zvol_write_iokit(offset 0x408a5000 bytes 0x1000)
FFFFB706C0317380:zvol_write_iokit(offset 0x40894000 bytes 0x1000)
```

Which is a bit surprising. Not entirely sure what going on. I get it is getting a dirstream, writing the name entry in, data for file, updating root CB. But.. this seems excessive.


Also, this code:

```
	sync = !(zv->zv_flags & ZVOL_WCE) ||
	    (zv->zv_objset->os_sync == ZFS_SYNC_ALWAYS);
```

Is wrong, all writes are currently sync. I think the ZVOL_WCE logic is from osx. We should check whatever the Windows equivalent might be, either for the IRP itself, or whatever might be in the storport request.

**Comment by lundman** [comment]
Also, this doesn't seem right, shouldn't delay be decremented:
```
	while (pWkRtnParms->SecondsToDelay) {
		LARGE_INTEGER delay;

		delay.QuadPart = -10 * 1000 * 1000 * pWkRtnParms->SecondsToDelay;

		KeDelayExecutionThread(KernelMode, TRUE, &delay);
	}
```

**Comment by tamlin-mike** [comment]
> shouldn't delay be decremented

Not sure, but that `while` should probably be an `if`. In case `SecondsToDelay` is signed it should also make sure it's positive.

Unless it's critical to wait for that amount of seconds, it's probably OK to continue to disregard any early aborted wait return value. If it is critical, since it's waiting alertable (**TRUE**) the return value from KeDelay* should be checked too.

Additionally, if there is _any_ risk any other thread could change that instance of `SecondsToDelay`, it should be captured in a local var.

**Comment by lundman** [comment]
I'm not sure the amplification is our fault. If I write a single 1MB block, that writes comes in fine, offset and length. Then for some reason that write is repeated a few more times, same offset and length. Of course, with COW that is a bad thing.

Why are the write requests coming in multiple times? Tried both ntfs and fat32.

**Comment by lundman** [comment]
Ok on the other thing `pWkRtnParms->SecondsToDelay` is never set to a value, its zero from `RtlZeroMemory(pWkRtnParms, sizeof(MP_WorkRtnParms));` and I see no Delay related value in `PSCSI_REQUEST_BLOCK` so I have no idea where I got that idea from.

**Comment by lundman** [comment]
OK, a more controlled test run:

Additional statistics:
```
		static uint64_t total_written = 0ULL;
		status = zvol_write(zv, uio);
		atomic_add_64(&total_written, pSrb->DataTransferLength);
		dprintf("TotalWritten: %llu (%llu MBytes)\n", total_written,
			total_written >> 20ULL);
```
So we know exactly how much we have passed down to ZFS/zvol.

```
# Start with new ZVOL
$ ./zfs create -s -V 3GB -b 512 tank/vol                                        

# Write exactly 100MB of uncompressable data to the raw device:
$ dd if=/dev/urandom of=/dev/sdc bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 133.087 s, 788 kB/s

# Check cbuf log output
FFFFB706CADE5040:zvol_write_iokit(offset 0x63f0000 bytes 0x10000)
FFFFB706CADE5040:TotalWritten: 104857600 (100 MBytes)
FFFFB706C645D080:ZFS: ioctl sizes: in 4540 out 4540: cmd 9c402013

# How much space did we consume in ZFS?
$ ./zfs list
NAME       USED  AVAIL  REFER  MOUNTPOINT
tank/vol   817M  17.9G   817M  -

$ ./zfs get used,referenced,usedbydataset,written,logicalused,logicalreferenced  tank/vol
NAME      PROPERTY           VALUE    SOURCE
tank/vol  used               817M     -
tank/vol  referenced         817M     -
tank/vol  usedbydataset      817M     -
tank/vol  written            817M     -
tank/vol  logicalused        109M     -
tank/vol  logicalreferenced  109M     -

$ ./zpool list
NAME   SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
tank  19.5G   999M  18.5G        -         -     0%     5%  1.00x  ONLINE  -

```

Which seems the problem is on ZFS side. We are handed 100MB of data, and pull another 700MB out of a hat. Since logicalused is correct, do we have a recordsize/volblocksize problem?

**Comment by tamlin-mike** [comment]
I massaged the zvol_write_iokit log a bit, to see if I could spot a pattern, and...
```
A=FFFFB706C0313080:zvol_write_iokit
B=FFFFB706C0317380:zvol_write_iokit

A(@ 0x408b1000 8KB)
A(@ 0x1644000 64KB)
A(@ 0x1654000 64KB)

B(@ 0x1664000 64KB)
B(@ 0x1674000 64KB)
B(@ 0x1684000 64KB)
B(@ 0x1694000 64KB)
B(@ 0x16a4000 64KB)
B(@ 0x16b4000 64KB)

A(@ 0x16c4000 64KB)
A(@ 0x16d4000 64KB)
A(@ 0x16e4000 64KB)
A(@ 0x16f4000 64KB)
A(@ 0x1704000 64KB)

B(@ 0x1714000 64KB)
B(@ 0x1724000 64KB)

A(@ 0x1734000 64KB)
A(@ 0x1744000 64KB)
A(@ 0x1754000 64KB)
A(@ 0x1764000 64KB)

B(@ 0x1774000 64KB)
B(@ 0x1784000 64KB)
B(@ 0x1794000 64KB)
B(@ 0x17a4000 64KB)
B(@ 0x17b4000 64KB)
B(@ 0x17c4000 64KB)
B(@ 0x17d4000 64KB)

A(@ 0x17e4000 64KB)
A(@ 0x17f4000 64KB)

B(@ 0x1804000 64KB)
B(@ 0x1814000 64KB)
B(@ 0x1824000 64KB)
B(@ 0x1834000 bytes 0xf000)
B(@ 0x1843000 4KB)          // actual data block? To ZIL?

A(@ 0x408a2000 4KB)         // actual data block? To data area?
A(@ 0x1434800 bytes 0x7a00)
A(@ 0x143c200 bytes 0x7a00)
A(@ 0x1434800 bytes 0x7a00) // 0x1434800 again
A(@ 0x143c200 bytes 0x7a00) // 0x143c200 again
A(@ 0x1434800 bytes 0x7a00) // 0x1434800 again
A(@ 0x1444000 bytes 0x200)

B(@ 0x143c200 bytes 0x7a00) // 0x143c200 again
B(@ 0x1434800 bytes 0x7a00) // 0x1434800 again

A(@ 0x408b2000 4KB)         // NOTE: This overlaps half of the very first write 0x408b1000 + 8KB
A(@ 0x1444200 bytes 0x200)

B(@ 0x143c200 bytes 0x7a00) // 0x143c200 again
B(@ 0x1434800 bytes 0x7a00) // 0x1434800 again
B(@ 0x408a2000 4KB)         // 0x408a2000 again (actual data block?)
B(@ 0x1844000 4KB)
B(@ 0x408b5000 64KB)
B(@ 0x408a5000 4KB)
B(@ 0x40894000 4KB)
```
Could the 0x1[678]* offsets be ZIL, or would that be the 0x4* offsets? 0x14* a root block?

As for NT synch vs. asynch writes, here are some ideas
Created by: IoBuildSynchronousFsdReques vs. IoBuildAsynchronousFsdRequest
Checked by: FileObject->Flags, FO_SYNCHRONOUS_IO . See e.g. https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-write

**Comment by lundman** [comment]
The sync writes tho, since I'm a handler of storport, I don't know if I'm actually passed any flag in IRP - if there was one, presumably storport would offer it to me? Similarly, I don't get an "open" request I don't think, unless it's the FindTarget handler.

**Comment by tamlin-mike** [comment]
Mea culpa. I was thinking it was a zfs (filesystem) issue, hence the mention of `FileObject` above. I'm now getting the impression it's about the blockdevice handler. Please disregard any misinformed comments from me.

**Comment by aviksildc** [comment]
@lundman I am using latest ZFSin release (Hagliga) debug version on a Windows Server 2016 VM. However my observation is different regarding the write amplification. I created a similar zvol and wrote 100MB to it using dd for Windows. But don't see much write amplification in zpool:

```
> zfs create -s -V 8g -b 512 zpool10g/zvol8g
```
```
> wmic diskdrive list brief
Caption                           DeviceID            Model                             Partitions  Size
VBOX HARDDISK                     \\.\PHYSICALDRIVE1  VBOX HARDDISK                     2           10733990400
VBOX HARDDISK                     \\.\PHYSICALDRIVE0  VBOX HARDDISK                     2           53686402560
OpenZFS WinZVOL SCSI Disk Device  \\.\PHYSICALDRIVE2  OpenZFS WinZVOL SCSI Disk Device  0           8587192320
```
```
> zfs get used,referenced,usedbydataset,written,logicalused,logicalreferenced zpool10g/zvol8g
NAME             PROPERTY           VALUE    SOURCE
zpool10g/zvol8g  used               12K      -
zpool10g/zvol8g  referenced         12K      -
zpool10g/zvol8g  usedbydataset      12K      -
zpool10g/zvol8g  written            12K      -
zpool10g/zvol8g  logicalused        6K       -
zpool10g/zvol8g  logicalreferenced  6K       -
```
```
> .\ddrelease64.exe if=100MBfile of=\\.\PHYSICALDRIVE2 bs=1M count=100
rawwrite dd for windows version 1.0beta1 WIN64.
Written by John Newbigin <jnewbigin@chrysocome.net>
This program is covered by terms of the GPL Version 2.

100+0 records in
100+0 records out
```
```
> zfs get used,referenced,usedbydataset,written,logicalused,logicalreferenced zpool10g/zvol8g
NAME             PROPERTY           VALUE    SOURCE
zpool10g/zvol8g  used               115M     -
zpool10g/zvol8g  referenced         115M     -
zpool10g/zvol8g  usedbydataset      115M     -
zpool10g/zvol8g  written            115M     -
zpool10g/zvol8g  logicalused        108M     -
zpool10g/zvol8g  logicalreferenced  108M     -
```
Let me know if I am missing something.

**Comment by lundman** [comment]
I think it is the new zvol code that adds the _dnode methods. Let me spit out an installer

**Comment by lundman** [comment]
http://www.lundman.net/OpenZFSOnWindows-debug-20200410.exe

**Comment by aviksildc** [comment]
> http://www.lundman.net/OpenZFSOnWindows-debug-20200410.exe
Installed this build:
```
PS C:\Windows\System32\drivers> ls .\ZFSin.sys


    Directory: C:\Windows\System32\drivers


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        4/10/2020   6:44 PM        3707392 ZFSin.sys
```
Even with this this build I don't see any significant write amplification:

```
>zfs get used,referenced,usedbydataset,written,logicalused,logicalreferenced zpool10g/zvol8g
NAME             PROPERTY           VALUE    SOURCE
zpool10g/zvol8g  used               115M     -
zpool10g/zvol8g  referenced         115M     -
zpool10g/zvol8g  usedbydataset      115M     -
zpool10g/zvol8g  written            115M     -
zpool10g/zvol8g  logicalused        107M     -
zpool10g/zvol8g  logicalreferenced  107M     -
```

**Comment by aviksildc** [comment]
Another interesting observation: for a single 4K write on a zvol, I see there are 87 writes to backend zpool totaling 204,800 bytes. I captured it using Xperf tracing tool and analyzed with Windows Performance Analyzer tool. Please find below the zipped tracing file. The Disk 1 is backend zpool and Disk 2 is the vanilla zvol of 8GB with default volblocksize.

[zvol_4kwrite.zip](https://github.com/openzfsonwindows/ZFSin/files/4461681/zvol_4kwrite.zip)

![image](https://user-images.githubusercontent.com/60229901/78994335-697a0200-7b5d-11ea-910f-7601650e1c12.png)

**Comment by ahrens** [comment]
@lundman in your test case  https://github.com/openzfsonwindows/ZFSin/issues/239#issuecomment-611914295, what is your pool configuration (what is ashift, what is `pool list -v`)?

Your results are consistent with using 4K-sector disks (ashift=12).  You are writing 512-byte ZFS blocks (`zfs create -b 512`), each of which must be rounded up to a multiple of the sector size (4K), which would account for the need to allocate (and write) 8x as much as the "user data".

**Comment by lundman** [comment]
Ok, I can confirm that using ashift=12 and `-s 4096` has no amplification. I suspected a blocksize problem, but I was looking at volblocksize vs `dd bs=` in my tests, oh well :)  

@imtiazdc  If you redo zvol tests make sure that "ashift=12, -s 4096" for a 4k test, or "ashift=9, -s 512", etc.

**Comment by imtiazdc** [comment]
Hi @lundman,

@aviksildc is pursuing this issue within datacore. I will let him update this thread with his findings. I will get back to you on the writers blocking issue.

**Comment by aviksildc** [comment]
With ```-o ashift=12``` for zpool, and ```-b 4096``` for zvol, on Windows, I don't see any <4K writes on the backend zpool for a single 4K zvol write, however I see about 78 writes totaling 520KB on the backend zpool:

![image](https://user-images.githubusercontent.com/60229901/79116124-4477d000-7da5-11ea-86ee-312379b05bc3.png)

[zvol_4kwrite_ashift12.zip](https://github.com/openzfsonwindows/ZFSin/files/4469268/zvol_4kwrite_ashift12.zip)

Also the behavior is similar on Linux as well. I used stock zfs in Ubuntu 18.04 and used ```blktrace``` tool to capture the data. For a single 4K zvol (volblocksize=4K) write I see there are about 70 writes to backend zvol totaling 528KB:

```
Total (8,16):
 Reads Queued:           0,        0KiB	 Writes Queued:          70,      528KiB
 Read Dispatches:        0,        0KiB	 Write Dispatches:       70,      528KiB
 Reads Requeued:         0		 Writes Requeued:         0
 Reads Completed:        0,        0KiB	 Writes Completed:       70,      528KiB
 Read Merges:            0,        0KiB	 Write Merges:            0,        0KiB
 IO unplugs:             0        	 Timer unplugs:           0
```

**Comment by lundman** [comment]
When you write to ZVOL, due to COW, it will update the blkptrs, traversing up the tree until it gets to the uberblock. It will also update some ZVOL metadata, I think. So even though you wrote 4K there is some overhead once the next spa_sync() is called (5s). In theory, it should be a similar-sized overhead if you write 4MB data instead of 4KB. (Or whatever amount can fit in one spa txg - assuming non-sync writes).

I think that is normal, whereas the 1MB -> 8MB writes were not.
