### ISSUE TITLE
How to install released binary?

### ISSUE THREAD

**Issue by testcaoy7** [openzfsonwindows/ZFSin#24]
I would like to try ZFS in VMware but I failed to find any instructions about installing released binary. I don't want to compile source code. I just want to try if latest build is working.

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin/releases

its a bit old now, but its enough to do what I did in the presentation.

**Comment by testcaoy7** [comment]
@lundman Thank you for your kind reply! I did downloaded the release. I just know how to install it. I right-clicked INF and installed it and I also install Visual C++ Redistributable 2015. But when I run zpool and zfs the system still says “VCRUNTIME140.DLL” and "ucrtbased.dll" is missing (which is not. I find them both in my system drive)

**Comment by testcaoy7** [comment]
@lundman zfs.exe and zpool.exe always says 
"Unable to open \\.\ZFS: No error."
"Failed to initialize the libzfs library."

My OS is Windows 10 LTSB and I install the driver as well as VS 2017.

**Comment by lundman** [comment]
That would be because the kernel driver isn't loaded, the zfsin.sys file needs to be "installed". In theory, I think you can right click the .inf file and pick install, but I have never tried it. You can also copy the .sys file to system32/ and reboot - I think.

**Comment by testcaoy7** [comment]
No luck ...
I did tried using INF file to install the driver.
I also tried copying SYS file to the System32, SysWOW64 and Syetem32\drivers ...
The driver simply won't load.
Maybe it is the VMware issue?

**Comment by lundman** [comment]
I use VMware myself, but I have never tried getting a binary .sys to run by itself - I always deploy with VisualStudio... eventually I'll figure out what to do with installing, but not really close to that phase :)

**Comment by testcaoy7** [comment]
OK ~
It appears I have to compile the code my self ~
I shall try.

**Comment by gamlerhart** [comment]
Yes, I recommend going through the compile / deploy with VS right now.

To install it in a regular machine, you need to disable signed drivers etc etc. 
I don't remember the steps.

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin#installing-a-binary-release

**Comment by testcaoy7** [comment]
@lundman Thank you. I shall try it as soon as I have some spare time.

**Comment by lundman** [comment]
Feel free to give feedback, did it run, how far you got etc. I also hang out in freenode #openzfsonwindows (near empty) and #openzfsonosx

**Comment by testcaoy7** [comment]
I get the drive running. However, there are some questions as well. 
1、Which partition table should I use? MBR or GPT
2、Before creating ZFS pools, do I need to create unformatted partitions at first?
3、I don't know howto get the drive name. 
By using command "Get-WmiObject Win32DiskDrive" can list the physical hard drives‘ ID but when I use drive ID （“\\.\PHYSICASLDRIVE0” etc.）the ZFS driver reported  "cannot open '\\.\PHYSICALDRIVE0': Invalid argument". 
Then I tried mountvol.exe. It lists volumes, but when I use volume ID ("\\?\Volume{c0183c81-0000-0000-0000-100000000000}\" etc.) the ZFS drive reported "cannot use '\\?\Volume{c0183c81-0000-0000-0000-100000000000}\': must be a block device or regular file".

**Comment by lundman** [comment]
I'm working on the zpool create code at the moment, so you can't create a pool on disk in Windows. You can use the file-based-pool to play around, or create the pool on disk with another platform first.

But, hopefully soon, you will be able to give a raw disk to zpool, and it will partition it the way ZFS likes, and so on.

**Comment by testcaoy7** [comment]
@lundman I see. Thank you.

**Comment by lundman** [comment]
4d4dc9f3b766deb604dedc55b242dbdeddf5867f
