### ISSUE TITLE
ZFS needs to open disks exclusively.

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/ZFSin#269]
It appears that if you create/import a pool with a bunch of disks, even though these disks are "in use", you can still do naughty things to them. Like partition the disk, format the disk, etc.

In Unix world, you can open the /dev/disk node and have exclusive access to the disk, and other attempts to open it (write mode) will return EBUSY.

I removed `FILE_SHARE_WRITE` from the `ZwCreateFile()` call, thinking it would do "the right thing" but it appears not.

So we need to figure out how you can exclusively take a disk resource and prevent the user from doing silly things to it, while it is imported.

**Comment by lundman** [comment]
Scott_Noone suggests:

> Any reason to not just mark the disk as hidden with IOCTL_DISK_SET_DISK_ATTRIBUTES? That disables the disk's device interface so no one else can find it through PnP. For reference, this is what Storage Spaces does when you assign a disk to a pool.
> 
> If you also mark it offline then the partition PDOs are deleted as well, so no one is going to try to make a volume out of the disk either.

**Comment by lundman** [comment]
Trying Noone's suggestion:
https://github.com/openzfsonwindows/ZFSin/pull/270

**Comment by datacore-tlaurent** [comment]
I tried with commit #270 but the pool cannot be imported.
<<
cannot import 'zfsp1': one or more devices is currently unavailable
>>
I see the physical disk going offline briefly, which is what we want, but that also prevents ZFSin itself accessing the device. then the pool import fails and disks return to an online state.

**Comment by lundman** [comment]
I have one concern then, since it is marked offline when kernel opens it, and online when we close the handle - is there some small chance we don't close it always? It has never been an issue on other platforms though. My one test succeeded successfully :)

If you have worked on making it better, please push a commit onto this PR - we might have to figure out permissions though.

If you want registry enhancement, that is fine by me.

**Comment by datacore-tlaurent** [comment]
The best way is to have ZFSin protect the disk as long as it is in a zpool so it should be turned back online only if the physical disk is removed from the zpool (meaning that "zpool export" should not online it even if the physical disk handle gets closed.  That is my feeling without knowing all the intricacies of the code but I'll check it.

**Comment by lundman** [comment]
The way ZFS work on all platforms, is that when you export your pool, the disks are released as normal disks, ready for the user to format, or change, or plug into a different system. In that sense, zpool destroy and zpool export are the similar.

One large difference is of course that we should automatically import pools upon boot, that were not exported. This piece is missing. Normally, you would not export pools. 

But, it definitely would be nice if they were more easily identifiable, in say DiskManager, when exported, as "ZFS labelled disk" or something, right now, they look totally free to use.
