### ISSUE TITLE
Windows equivalent of scripts/make_gitrev.sh

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/ZFSin#271]
When compiling on Unix, Makefiles run `scripts/make_gitrev.sh` which produces `include/zfs_gitrev.h` file, containing:

```
#define	ZFS_META_GITREV "zfs-0.8.0-947-g461c4dd8b-dirty"
```
which is the output from `git describe --always --long --dirty`

We should preferably do something similar. There appears to be a PreBuildEvent in Devstudio, which
seems most people use Powershell scripts to do what they want.

Luckily, @michaeldexter  is the self proclaimed PS expert, so he's probably keen :)

**Comment by kusuriya** [comment]
Can you point me at `scripts/make_gitrev.sh` my search fu seems to be failing me and I can't find it.
But without more than what you have described this is pretty easy and could be knocked out pretty quick. I just would like to see the source script so I can do a fullish port of it.

**Comment by lundman** [comment]
https://github.com/openzfsonosx/openzfs/blob/master/scripts/make_gitrev.sh
although I see they've moved it inside the Makefile in upstream:
https://github.com/openzfs/zfs/blob/master/Makefile.am#L55

but it does the same. The only trick is that if the new gitrev is identical to the existing, it shouldn't update the file (to avoid recompiling things). Looks like the new version opted to write a tmp file, diff, and rename if different.

**Comment by lundman** [comment]
Fixed in OpenZFS's cmake files.
