### ISSUE TITLE
Windows 8.1, Not working at all

### ISSUE THREAD

**Issue by BullShark** [openzfsonwindows/ZFSin#278]
I installed the 0.23 release in Windows 8.1. I rebooted. The drive with zfs is not detected. I tried installing again and rebooting again. Nothing at all changed. See the screenshot.

![zfs windoze](https://user-images.githubusercontent.com/1526595/86418632-5e36fe00-bc96-11ea-9ff5-9ef84092b521.PNG)

**Comment by lundman** [comment]
Presumably the ZFSin.sys driver doesn't load due to some function(s) that aren't supported by Win8.1 - Wonder what they could be, and if there is a way to get it to tell us which.

**Comment by BullShark** [comment]
Maybe you could download Windows 8.1 and try it in a VM like Virtual Box or VMWare to see?

https://www.microsoft.com/en-us/software-download/windows8ISO

Let me know if you'd like me to submit some Windows logs and which ones.

**Comment by lundman** [comment]
OK, so this is what I learnt. The install log is apparently C:/Windows/inf/setupapi.dev.log; in that, i get
`code 37 CM_PROB_FAILED_DRIVER_ENTRY`.

Searching on that came up with the suggestion to run `Depends.exe` to find out what fails to link;
It lists; `MSRPC.SYS STORPORT.SYS WDFLDR.SYS`

Storport surprises me a bit, as I went that route with the recommendation of the nt-dev guys. The other two are unfamiliar to me.

![Screen Shot 2020-07-03 at 1057 14 (2)](https://user-images.githubusercontent.com/637168/86424053-72254300-bd1c-11ea-882b-462f4f9e9a9e.png)

**Comment by BullShark** [comment]
I have no idea. If it was Linux, I probably could help.

I found many results searching that error message.

https://www.google.com/search?client=firefox-b-1-d&q=error+at+least+one+required+implicit+or+forwarded+dependency+was+not+found

**Comment by BullShark** [comment]
Here is my C:/Windows/inf/setupapi.dev.log if it helps.
[setupapi.dev.log](https://github.com/openzfsonwindows/ZFSin/files/4867581/setupapi.dev.log)

**Comment by lundman** [comment]
OK so all three files it complains about, are in Windows/system32/drivers, and if I copy them into the same place as ZFSin.sys, the Depends.exe util comes up with no errors. Wonder I am supposed to set dependencies to them, so they are automatically loaded.

**Comment by lundman** [comment]
Aha, ok, I built the SYS for Win10 Universal. Let me build one for "Desktop" and Win8

**Comment by lundman** [comment]
https://openzfsonosx.org/wiki/Windows_builds

**Comment by BullShark** [comment]
> 
> 
> https://openzfsonosx.org/wiki/Windows_builds

I can't wait to try it. I think you forgot to upload it.

![image](https://user-images.githubusercontent.com/1526595/86443880-8265ff80-bcd5-11ea-880e-65071b788d5e.png)

**Comment by lundman** [comment]
heh, no, forgot I stuck Win8 on the name, one sec

**Comment by lundman** [comment]
Ok updated:  http://www.lundman.net/OpenZFSOnWindows-debug-20200703-Win8x64.exe

**Comment by BullShark** [comment]
It's not fixed for me. I have dependency walker. I am getting the same error about missing files. I am using the one from your link to install.

![image](https://user-images.githubusercontent.com/1526595/86466733-cbc84600-bcf9-11ea-901a-1e4980d03996.png)

**Comment by BullShark** [comment]
> OK so all three files it complains about, are in Windows/system32/drivers, and if I copy them into the same place as ZFSin.sys, the Depends.exe util comes up with no errors. Wonder I am supposed to set dependencies to them, so they are automatically loaded.

I did this. I copied the files. 

![image](https://user-images.githubusercontent.com/1526595/86498624-3e621180-bd4c-11ea-9a0c-cb60ae1f1ccd.png)

Then I did a reboot.

I am still receiving this message.

```
$ zpool status
Unable to open \\.\ZFS: No such file or directory.
Verify the ZFS module stack is loaded by running '/insert windows magic here/' as root.
The /dev/zfs device is missing and must be created.
Try running 'udevadm trigger' as root to create it.
```

**Comment by lundman** [comment]
Indefinitely had it loading over debugger, but maybe I stuffed something up during packaging - I'll try the installer myself to make sure

**Comment by lundman** [comment]
I tried Win8 install from yesterday, and it didn't work. So I tried today's Win7 install, and then  it worked. So either the recompile today helped, or that I installed it twice? Odd.

**Comment by BullShark** [comment]
No error from "zpool status", but the pool is not found from the command.

The drive with an encrypted zfs pool and dataset I created in Linux is not showing in Windows Explorer.

The Partition Manager seems the drive and pool.

![image](https://user-images.githubusercontent.com/1526595/86533892-ff41d680-be99-11ea-9f18-0170c5ff5d81.png)

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/86534169-d8849f80-be9b-11ea-8724-4ef9288d50f2.png)

**Comment by BullShark** [comment]
Read Only???? That's not good!

![image](https://user-images.githubusercontent.com/1526595/86534198-1386d300-be9c-11ea-9f55-bda6ea98840d.png)

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/86534287-e71f8680-be9c-11ea-94d9-959bc192d017.png)

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/86534324-24841400-be9d-11ea-8465-6e2afc2c07c1.png)

**Comment by BullShark** [comment]
Error.

![image](https://user-images.githubusercontent.com/1526595/86534814-1fc15f00-bea1-11ea-8175-3c7b84850425.png)

**Comment by BullShark** [comment]
Reproduce the bug:

1. Download Manjaro with KDE from here.

https://manjaro.org/download/#kde-plasma

2. Run in Virtual Box or USB Drive with Rufus.

https://rufus.ie/

3. Open Konsole and

sudo passwd root
sudo su -
pacman -S zfs-dkms zfs-utils
zpool create -O encryption=on -O keyformat=passphrase -O keylocation=prompt -f storage /dev/sde

4. Now try using the drive in Windows 8.1.

**Comment by BullShark** [comment]
![image](https://user-images.githubusercontent.com/1526595/86535115-8b0c3080-bea3-11ea-94bd-72cd4955b21a.png)

**Comment by lundman** [comment]
The readonly was because objquota and projectquota was enabled, two features that ZFSin do not yet understand, create a pool without those features.
Use `zpool import -l` to have it ask for passwd on import.
Give up on driveletter for now, there is an issue for it, as it doesnt work for the pool.

**Comment by Aerol** [comment]
> Give up on driveletter for now, there is an issue for it, as it doesnt work for the pool.

How does one use the zfs pool in Explorer without assigning a drive letter?

**Comment by lundman** [comment]
It gives you the first available driveletter (instead of a specific one). You can run `zfs mount` to see what was assign. You often need to push F5 in Explorer to fresh it to show.

**Comment by BullShark** [comment]
> 
> 
> The readonly was because objquota and projectquota was enabled, two features that ZFSin do not yet understand, create a pool without those features.

Would this be correct for creating a pool and dataset with encryption and those 2 features disabled in the pool?

```
zpool create -O encryption=on -O keyformat=passphrase -O keylocation=prompt -o feature@userobj_accounting=disabled -o feature@project_quota=disabled -f storage /dev/sde 
```

**Comment by lundman** [comment]
I believe you have to use `zpool create -d` where -d disables everything, then you can turn the features you want back on again. It's a bit of a pain, but fixes for that is suppose to come from upstream.

**Comment by BullShark** [comment]
Filesystem features can be turned on and off after creation. Pool features cannot be toggled on and off after creation. So far, everything is good using my command.
