### ISSUE TITLE
Enjun cannot import pool on physical drive.

### ISSUE THREAD

**Issue by arturkow2000** [openzfsonwindows/ZFSin#292]
ZFSin no longer detects pools starting with enjun release, on Hagliga it worked fine.
zpool import detects physical disks and all partitions located on them properly but not pools.

zpool.exe import
path '\\?\ide#disktoshiba_dt01aca100______________________ms2oa750#5&17ef7b8e&0&0.0.0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive0'
read partitions ok 5
    gpt 0: type 4f57d710 off 0x100000 len 0x800000
    gpt 1: type 4f57d710 off 0x900000 len 0x1000000
    gpt 2: type 4f57d710 off 0xd100000 len 0xc800000
    gpt 3: type 4f57d710 off 0x19900000 len 0xd01a900000   <----- pool here
    gpt 4: type 4f57d710 off 0xd034200000 len 0x18782bea00
asking libefi to read label
EFI read OK, max partitions 128
    part 1:  offset 4800:    len 8000:    tag: 10    name: 'Microsoft reserved partition'
    part 2:  offset 68800:    len 64000:    tag: 16    name: ''
    part 3:  offset cc800:    len 680d4800:    tag: 18    name: ''
    part 4:  offset 681a1000:    len c3c15f5:    tag: 11    name: 'Basic data partition'
path '\\?\ide#diskspcc_solid_state_disk___________________q0616b0_#5&2aa92c33&0&1.0.0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive1'
read partitions ok 5
    gpt 0: type 4f57d710 off 0x100000 len 0x1300200
    gpt 1: type 4f57d710 off 0x1500000 len 0x17c00000
    gpt 2: type 4f57d710 off 0x19100000 len 0x1000000
    gpt 3: type 4f57d710 off 0x1a100000 len 0x1d9555e000
    gpt 4: type 4f57d710 off 0x1daf700000 len 0x1ff00000
asking libefi to read label
EFI read OK, max partitions 128
    part 1:  offset a800:    len be000:    tag: c    name: ''
    part 2:  offset c8800:    len 8000:    tag: 10    name: 'Microsoft reserved partition'
    part 3:  offset d0800:    len ecaaaf0:    tag: 11    name: 'Basic data partition'
Processing volume '\\?\Volume{2f7e4ba3-c844-4fca-a1f9-a7e0be6beac2}'
Processing volume '\\?\Volume{9af347e7-0166-4159-845e-e526ee41852e}'
Processing volume '\\?\Volume{992ac392-d0f5-4a8b-8df6-cacae3ee7586}'
Processing volume '\\?\Volume{53f6284f-1e45-4d58-a55d-822066e43aab}'
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
no pools available to import

Pool still works well in both Linux and FreeBSD.
Importing file based zpools works fine.

**Comment by andreascschmidt** [comment]
I think the latest version is not able to import **ANY** existing pool. 
I have a pool zfs-linux made from linux which cannot be imported. 

 zpool import
path '\\?\scsi#disk&ven_corsair&prod_force_le_ssd#4&1636555b&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive0'
read partitions ok 9
    gpt 0: type c54fdc00 off 0x100000 len 0x1c200000
    gpt 1: type c54fdc00 off 0x1c300000 len 0x6400000
    gpt 2: type c54fdc00 off 0x22700000 len 0x1000000
    gpt 3: type c54fdc00 off 0x23700000 len 0x25d8842400
    gpt 4: type c54fdc00 off 0x25fc000000 len 0x1dd00000
    gpt 5: type c54fdc00 off 0x2619e00000 len 0x1d000000
    gpt 6: type c54fdc00 off 0x2636f00000 len 0x1c400000
    gpt 7: type c54fdc00 off 0x2653300000 len 0x737c00000
    gpt 8: type c54fdc00 off 0x2d8af00000 len 0xa59900000
asking libefi to read label
EFI read OK, max partitions 128
    part 1:  offset e1800:    len 32000:    tag: c    name: 'EFI system partition'
    part 2:  offset 113800:    len 8000:    tag: 10    name: 'Microsoft reserved partition'
    part 3:  offset 11b800:    len 12ec4212:    tag: 11    name: 'Basic data partition'
    part 7:  offset 13299800:    len 39be000:    tag: 11    name: 'Basic data partition'
    part 9:  offset 16c57800:    len 52cc800:    tag: 11    name: 'Basic data partition'
path '\\?\scsi#disk&ven_&prod_st500dm002-1bd14#4&1636555b&0&010000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive1'
read partitions ok 4
    mbr 0: type 83 off 0x100000 len 0x315ef00000
    mbr 1: type 7 off 0x315f000000 len 0x4311c00000
    mbr 2: type 0 off 0x0 len 0x0
    mbr 3: type 0 off 0x0 len 0x0
asking libefi to read label
Processing volume '\\?\Volume{1c64720f-e77f-476e-90b1-50e38bbdce9e}'
Processing volume '\\?\Volume{296744f8-6242-42f9-ac04-9fbd36d43617}'
Processing volume '\\?\Volume{1399691f-91eb-44d8-b72a-12b57b719375}'
Processing volume '\\?\Volume{8bde66b8-e073-4275-8ad1-f0b6748d9d0f}'
Processing volume '\\?\Volume{08f866e7-c367-468f-940f-bad63dc5b553}'
Processing volume '\\?\Volume{0005ec1f-91a0-3225-22fc-fd133ed80b00}'
Processing volume '\\?\Volume{fecf7930-7422-01d4-9894-457f113aea00}'
Processing volume '\\?\Volume{3d9ebbee-0000-0000-0000-005f31000000}'
Processing volume '\\?\Volume{08d3150d-70fa-4e95-bf8d-f86386d50d36}'
Processing volume '\\?\Volume{5c79354b-7c27-11ea-943c-806e6f6e6963}'
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
no pools available to import

**Comment by lundman** [comment]
Ah that is a concern, I'll dig into it.

**Comment by lundman** [comment]
OK, `git bisect` tells me it is commit 7a5f8f6bd2285006877d09df88f12cfb3ae20167 - looking into why.

Would have been discovered right away with automatic testing, so maybe I should make that a higher priority :)

**Comment by lundman** [comment]
Apologies for the misdiagnosis.  Turned out that the import code was relying on file seek offset. Means the zpool labelclear will also need fixing (it currently has no virtual partition logic).
48cdbf1

**Comment by arturkow2000** [comment]
Works fine now, closing.
