### ISSUE TITLE
install fail on updated win10

### ISSUE THREAD

**Issue by raysar** [openzfsonwindows/ZFSin#30]
Hello,
I try to install zfs on win10entreprise on my laptop (no vm) after reading the install procedure.
![zfs win10](https://user-images.githubusercontent.com/6623125/37880766-a294284e-308d-11e8-8679-4036e33fedf5.png)

What can i do?

**Comment by lundman** [comment]
I assume you ran cmdline "as administrator". I believe devcon.exe dumps a log file in `system32\inf` of all places.

**Comment by 1warpengine** [comment]
It does not work with devcon on Win10 or Win2016 server, you need to manually install the driver.
Right click on the .inf and select INSTALL... then from Devices look for an unknown device, reinstall the driver by manually selecting the folder where you have your ZFS files. That worked for me.

**Comment by lundman** [comment]
It is a little annoying that each Windows PC seems to require different install procedure.. This is the part I know the least about, presumably there must be a simple to use installer-maker app that everyone uses that I should look into. The Windows specific things like that is what i know the least :)

**Comment by aabc123** [comment]
We've always used http://wixtoolset.org.  Integrates nicely in to VisualStudio.  It was fairly trivial to get it to install, start and stop Windows services but I don't think we used it for our custom driver.  I think for that we just right-clicked the INF (but then we were shipping the PCs that needed the driver, not asking users to install it).

But given in can run admin-privileged stuff, I can't see why it couldn't handle driver installation, but will probably need signed drivers at some point.  That will be the biggest sticking point for most users.

**Comment by aabc123** [comment]
There's a Wix extension http://wixtoolset.org/documentation/manual/v3/xsd/difxapp/driver.html for installing drivers and and and example (albeit old, from 2013) here: https://www.codeproject.com/Articles/573183/EchoInst-An-Example-Wix-Install-of-the-WDK-Echo-Dr

It's something I'd be happy to do but unfortunately time isn't readily available at the moment.  But if no-one else gets to first then it's something I could look at doing in the next 2-3 months possibly.

**Comment by michaeldexter** [comment]
The installer from 20180529 appears to work.

**Comment by fire** [comment]
Is this bug resolved?

**Comment by lundman** [comment]
Probably, many changes has been done with installer. If there are still issues, open a new ticket.
