### ISSUE TITLE
Import hangs with build 1.0.216

### ISSUE THREAD

**Issue by adamdmoss** [openzfsonwindows/ZFSin#312]
My pool import hangs with https://ci.appveyor.com/project/lundman/zfsin/builds/35813886 - zpool doesn't return and the datasets aren't mounted/available.
1.0.213 / https://ci.appveyor.com/project/lundman/zfsin/builds/35700991 seems good.

**Comment by adamdmoss** [comment]
Sorry for lack of details, I wanted to get back to a working system without spending too much time diagnosing.
FWIW I switched between 1.0.213 and 1.0.216 a few times to verify.

**Comment by lundman** [comment]
Hmm so a recent break? Thanks for reporting it
