### ISSUE TITLE
Stuck when export a pool create by O3X

### ISSUE THREAD

**Issue by livin2** [openzfsonwindows/ZFSin#331]
tank is a pool created by https://openzfsonosx.org/
1.` zpool import tank` (mountpoint is D:\)
2. copy some thing into D:\
3. `zpool export -f tank`
stuck with `zunmount(tank,D:\ ) running`

 after `MOUNTVOL D: /D`  it stuck with `zunmount(tank,tank) running`

OS Version:Windows10 1909(18363.1316)

**Comment by lundman** [comment]
The export/unmount bug has been one of the longest standing issues, I'm well aware of it, and I'd love to find the solution for it :)
