### ISSUE TITLE
Is FC HBA WMI functionality required? 

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/ZFSin#343]
ZFSin is currently registered as provider for  'MSFC_HBAAdapterMethods_GUID' class. It has not implemented many methods of this class and one of them is 'GetDiscoveredPortAttributes'.  This is causing problem when SCCM is installed on the same machine as it tries to execute this missing method after querying for this class. 

In our WMI code implementation, there is a comment saying that the support for fiber channel HBA is only for illustration. ("Note: The support for MSFC GUIDs is only illustrative, showing how to produce plausible results").  Can you please share your thoughts whether this and other WMI FC classes are expected to be supported (as provider) by the storport or required for any other functionality? If it is required, then we have to again set dummy values for this method response also.

**Comment by lundman** [comment]
Hmm must have missed this one, and it is a little beyond my current knowledge of this area. If there is a comment, it is from the storport example source I plugged in. I assume you guys know more in this area and can make the big decisions for us :)
