### ISSUE TITLE
QuickPrint dekstop application on mac

### ISSUE THREAD

**Issue by roopa01** [openzfsonwindows/ZFSin#346]
Hi,

  I am working on Quickprint project on mac .I am using catalina OS and xcode version 12.4. So that i am trying development setup to debug the code and i am upgrading Qt 5.15 to 6.2.3.There are some compilations error like 
Unknown type name 'byte' in type_trait
Unknown type name '_integer' in type_trait
C++ requires a type specifier for all decelarations
Use of undecelared identifier 'byte'

I am not able to find out why these error are coming .If anyone have idea about these plz reply me.
Regards
roopa01

**Comment by yurikoles** [comment]
Hi,

And how is that related to the `OpenZFS on Windows port`?

**Comment by lundman** [comment]
You want me to move it?

**Comment by lundman** [comment]
Oh hmm, didn't even read it, but not sure it even belongs to zfs on osx either.

**Comment by yurikoles** [comment]
It's completely unrelated, it's about some Qt-based C++ app.
