### ISSUE TITLE
2018-05-29 Snapshot: lz4 compression not available

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#36]
While lz4 compression has been working, it is not enabled in this snapshot, either at pool creation time or after.

Confirmed with: openzfsonwindows

**Comment by lundman** [comment]
ok, so it seems when I create a pool, the feature flags are all messed up in `spa->spa_feat_refcount_cache`. Export and import lets me set them, so perhaps it is a problem with pool creation specifically.

**Comment by lundman** [comment]
The VERIFY3U around 
```
			VERIFY3U((*refcount_cache), ==,
		    (atomic_swap_64(refcount_cache, refcount)));
```
was being evaluated twice, which is why I took it out, leading to pools created without feature flags, and setting lz4 would fail.  Cherry-pick in the VERIFY* fix from ZOL, and it will evaluate correctly.
