### ISSUE TITLE
20180505 Release: zpool.exe import will not recognize a FreeBSD zpool

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#37]
Primary disk is a spinning disk with a standard FreeBSD bsdinstall(8) GPT/UEFI/MBR layout.

zpool.exe will not detect the zpool for importation but FreeBSD will recognize the Windows zpool on the second physical disk.

**Comment by michaeldexter** [comment]
Same behavior with 20180529 "release-test".

**Comment by jheuking** [comment]
fixed that in #38
