### ISSUE TITLE
access denied error 

### ISSUE THREAD

**Issue by jheuking** [openzfsonwindows/ZFSin#39]
When trying to access second level folders (and probably also deeper folders and maybe also files?) I get an access denied error. Editing files and folders on the top level is also not allowed.
File/folder creation on the top level works and I am even able to modify files that I have created in that session. But after a remount of the dataset I get an access error on that files, too.
I suspect the causal change was made somewhere between prerelease 0.03 and 0.04?

![capture](https://user-images.githubusercontent.com/39560536/40710019-dc569e34-63f7-11e8-8d10-f1456d838032.PNG)

**Comment by lundman** [comment]
```
IRP_MJ_CREATE: FileObject FFFFB00803F98080 related 0000000000000000 name '\Directory' flags 0x0 sharing 0x7 options 0x1000020 attr 0x0 DesAcc 0x120089
zfs_vnop_lookup: enter
zfs_vnop_lookup: converted name is '\Directory' input len bytes 20 (err 0)  CaseInsensitive
dispatcher: exit: 0xc0000022 AccessDenied Information 0x1 : IRP_MJ_CREATE

```

Decision made in `zfs_vnop_lookup()` for some reason

**Comment by jheuking** [comment]
seems to be fixed, thanks!
