### ISSUE TITLE
CACHE_MANAGER (34) See the comment for FAT_FILE_SYSTEM (0x23)

### ISSUE THREAD

**Issue by lundman** [openzfsonwindows/ZFSin#44]
The new CACHE code is not quite right, and will generate the above unhelpful error message. The CACHE code will be by-passed until it can be debugged properly.

**Comment by lundman** [comment]
Seems the code works ok when IRP_MJ_WRITE is enabled, but will die in IRP_MJ_READ, in the call to `CcCopyReadEx()`. All arguments visually inspected as OK, and it has been initialised before hand.

**Comment by c0debeef** [comment]
You can ask kernel related questions on forum
http://www.kernelmode.info/forum/

**Comment by lundman** [comment]
Interesting to note that with the latest VFS fixes, running with cache appears to work. Although I will leave it off until i feel the foundation is stable :)

**Comment by lundman** [comment]
After the big rewrite, it seems I can now enable cache support without triggering this, or other, problems.

![screen shot 2019-01-23 at 1242 01 2](https://user-images.githubusercontent.com/637168/51581714-8ac8e100-1f0c-11e9-8b0a-b7db78491040.png)
