### ISSUE TITLE
Date modified is missing on files that are moved from windows to zpool

### ISSUE THREAD

**Issue by jheuking** [openzfsonwindows/ZFSin#54]

**Comment by lundman** [comment]
More details? If I move a file over, I get Modified: and Accessed: times just fine, it is missing a Created: date though. Checked with Properties on a file.

**Comment by lundman** [comment]
OK I have fixed the CreateTime - turns out code should not set the time if passed zero.

759a4bbbd5ef7b305d24b6ecea61bc06537ee905

**Comment by jheuking** [comment]
There wasn't really much more to tell :smile: 
I just took some dummy .txt-files, copied/moved them to my zpool and got different behavior.
First file was copied, second was moved 
![capture](https://user-images.githubusercontent.com/39560536/43883612-f8a15cca-9bb3-11e8-91be-c39a2ce54061.PNG)

But looks like it works now, good work :+1:
