### ISSUE TITLE
ERROR  The DEMO version of QSetup may only be used for evaluation

### ISSUE THREAD

**Issue by anatolix** [openzfsonwindows/ZFSin#56]
Binary install says:

ERROR
The DEMO version of QSetup may only be used for evaluation
Setup Aborted!

**Comment by lundman** [comment]
`ALSO - any setup produced with the DEMO version will expire 5 days after compilation.`

Ah how tedious - but as I can't get the driver install to work correctly, I'll go find another solution for installer software.

**Comment by lundman** [comment]
We have stopped using qsetup
