### ISSUE TITLE
Driver cannot be uninstalled properly 

### ISSUE THREAD

**Issue by jheuking** [openzfsonwindows/ZFSin#60]
I used `devcon.exe install ZFSin.inf ROOT/ZFSin` to install the driver.

After that I tried to uninstall it through the device manager. Right-clicked "ZFSin Controller" -> Uninstall device, ticked "Delete driver software for this device." -> Uninstall -> Reboot.

When I execute  `zpool status` after that, I  get `no pools available`, so the driver is still there... 
Probably something wrong with the .inf file?

**Comment by lundman** [comment]
I had noticed that, it used to unload fine - but now when I try a `devcon.exe uninstall` I don't get a single printf from ZFS code. (or indeed, deploying/debug in VS a 2nd time will unload first). It is as if it doesn't get far enough to actually call the driver.

**Comment by jheuking** [comment]
I tried to infverf.exe and got this:
```
WARNING(2083) in C:\Users\JulianH\source\repos\ZFSin\ZFSin\ZFSin.inf, line 59: Section [defaultuninstall] not referenced or used.
WARNING(2083) in C:\Users\JulianH\source\repos\ZFSin\ZFSin\ZFSin.inf, line 64: Section [defaultuninstall.services] not referenced or used.
WARNING(2083) in C:\Users\JulianH\source\repos\ZFSin\ZFSin\ZFSin.inf, line 91: Section [zfsin.dllfiles] not referenced or used.
```

Maybe, if we use the Manufacturer-section instead of Defaultinstall, DefaultUninstall doesn't get executed anymore...?

**Comment by lundman** [comment]
Oh hmm maybe, I wouldnt have thought it might be INF involved, so thats a good idea

**Comment by lundman** [comment]
I suspect the SetupAPI log entry gives clues:

```

>>>  [DIF_REMOVE - ROOT\VOLUME\0000]
>>>  Section start 2018/09/13 15:50:09.108
      cmd: "C:\Program Files (x86)\Windows Kits\10\Testing\Runtimes\TAEF\te.processhost.exe"  /role=TestExecution /wexcommunication_connectionid=61B9F8FE-4120-431E-BD10-96DFCAE6A39E /stackframecount=50 /wexcommunication_protocol=ncalrpc
     dvi: No class installer for 'ZFSin controller'
     dvi: No CoInstallers found
     dvi: Default installer: Enter 15:50:09.110
     dvi:      {Remove DEVICE}
     dvi:           {Delete Device - ROOT\VOLUME\0000}
     dvi:                Devnode Status = 0x0180300b
     dvi:                CM_Query_And_Remove_Subtree_Ex returns 0x00000017
     dvi:                Devnode Status after CM_Query_And_Remove_Subtree_Ex = 0x0180300b
!    dvi:                Query-removal was vetoed by ROOT\VOLUME\0000 (veto type 1: PNP_VetoLegacyDevice)
!    dvi:                Setting needs reboot
!    dvi:                Query-and-Remove failed: 0x17: CR_REMOVE_VETOED.
     dvi:                Device Instance uninstalled.
     dvi:           {Delete Device - exit(0x00000000)}
     dvi:      {Remove DEVICE exit (0x00000000)}
     dvi: Default installer: Exit
<<<  Section end 2018/09/13 15:50:09.132
<<<  [Exit status: SUCCESS]
```

Time to decipher and figure out why it decides it has to reboot to uninstall, instead of calling the DriverUnload function

**Comment by jheuking** [comment]
I was able to uninstall the driver the way it is described here 
https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/using-an-inf-file-to-uninstall-a-file-system-filter-driver

using this cmdline, where I used the .inf file I uninstalled the driver with.
`RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultUninstall 129 path-to-uninstall-dir\infname.inf`

The parameter 129 should make the pc reboot in any case. (see here: https://docs.microsoft.com/en-us/windows/desktop/api/setupapi/nf-setupapi-installhinfsectiona)

This uninstalls the driver successfully, but oddly enough you have to call this line twice in order to make the system restart and uninstall the driver....

**Comment by lundman** [comment]
Actually, hmm, manual unload isn't so bad, just need to use it in installer, both for update and uninstall.

**Comment by jheuking** [comment]
I tried to modify the parameters of the service a bit, because you said it would have worked in the past.
Currently we have:
```
ServiceType      = 1
StartType        = 1                        ;SERVICE_SYSTEM_START
ErrorControl     = 1
```
but beforehand it was:
```
ServiceType      = 2
StartType        = 3                        ;SERVICE_DEMAND_START 
ErrorControl     = 1
```

I reverted this changes and it seems to work like expected. Maybe you could verify that?
Expected means, when I hit uninstall in the device manager, all the windows internal nodes for the device gets deleted (I guess), the service probably gets deleted, but the driver files still remain in the repository. 
I read somewhere that this is what should happen if you uninstall a device through the device manager, but don't ask me where...
But as you said, on long term the cleanest way would probably be to use an installer for install, update and removal.

**Comment by jheuking** [comment]
hmm... strange that everything could be removed as expected nevertheless...
Would try git bisect in the next step, maybe this will provide some useful information ...

**Comment by jheuking** [comment]
I've read [here](https://stackoverflow.com/questions/11451443/driverunload-not-called-on-windows-restart-shutdown) that the DRIVER_UNLOAD routine doesn't get called on shutdown, so we probably should call zfs_stop and spl_stop in IRP_MJ_SHUTDOWN anyways... (which we are reliably receiving every time on shutdown)
But still have no clue, why the routine doesn't get called on uninstall while everything else seems to have worked like expected...

> Ah, the solution is "easy". It's not being called at all. I had to look it up, though.
> 
> The Windows 2000 Device Driver Book: A Guide for Programmers states:
> 
> A driver's Unload routine is not called at system shutdown time.
> 
> Also see this thread.
> 
> If you have a WDM driver use DispatchShutdown (IRP_MJ_SHUTDOWN).
> 
> Also check out the WDK (7600) documentation on "shutdown dispatch routines [WDK kernel]" and "shutdown power management [WDK kernel]".

**Comment by lundman** [comment]
We should do nothing on `IRP_MJ_SHUTDOWN` since in fact it is just shutting down to reboot. No reason to cleanly release things there. But we do want to handle uninstall (to presumably load a newer version of the driver, one hopes).
 
I am certain it worked in the past to unload, but it is also possible that zfs isn't what changed, but newer Windows patches did. Perhaps it is time to ask on the windev ML

**Comment by jheuking** [comment]
have just built a hello world driver with just driver_entry and driver_unload and of course it doesn't work, nice 🙈
used [this instruction](https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/writing-a-very-small-kmdf--driver) and [this](https://msdn.microsoft.com/en-us/library/windows/hardware/ff564886(v=vs.85).aspx)
so I would assume, that our problem is in fact caused by some windows-changes, if I did nothing wrong with this sample driver...? Could try an older windows version, just to be sure...

**Comment by jheuking** [comment]
oh sorry, my fault. Just reviewed that with the latest version and the service is in fact stoppable and changes it state to STOP_PENDING after I hit uninstall in the device manager....
But after restart it is running again on my machine... Can you verify that? 
Maybe the service should be in state `STOPPED` to trigger the `DRIVER_UNLOAD` routine...? Just a guess...
Additionally we are actually presuppose that in the INF file to complete the uninstall anyway, don't we?

```
[DefaultUninstall.Services]
DelService = %ServiceName%,0x200      ;Ensure service is stopped before deleting
```

**Comment by lundman** [comment]
Bah, I can't get any of this to work in the VM, but then I can't even right-click install any more :)

But he demonstrated that he can unload the driver which is nice, then you can uninstall/delete the SYS file for reboot.

**Comment by jheuking** [comment]
The installation from context menu doesn't work anymore, because I traded in the Manufacturer-section for DefaultInstall in the INF file. 
Currently the installation only works with devcon. I guess it should also work with "rundll32.exe, setupapi.dll InstallHinfSection... " but I haven't found out how yet. But if we want to use the Install from the context menu we should take the DefaultInstall-Section instead of Manufacturer...

we probably could take all the uninstall steps manually, but this shouldn't be necessary if everything works correctly, should it? The DRIVER_UNLOAD still doesn't get called...

**Comment by jheuking** [comment]
so DRIVER_UNLOAD gets called if I strip down driver.c to this:

```
VOID ZFSin_Fini(PDRIVER_OBJECT  DriverObject)
{
	KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "ZFSin_Fini\n"));
	DbgBreakPoint();
	//zfs_stop();
	//spl_stop();
}

NTSTATUS DriverEntry(_In_ PDRIVER_OBJECT  DriverObject, _In_ PUNICODE_STRING RegistryPath)
{
	//NTSTATUS status;
	KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL, "ZFSin: DriverEntry\n"));
	DbgBreakPoint();
	// Setup global so zfs_ioctl.c can setup devnode
	WIN_DriverObject = DriverObject;
	WIN_DriverObject->DriverUnload = ZFSin_Fini;

	//spl_start();
	//zfs_start();

	return STATUS_SUCCESS;
}
```

Additionally I had to switch back to the DefaultInstall-Section and install the driver from the context menu as this procedure doesn't seem to create a device for the driver. It also works if the driver gets installed with the Manufacturer-Section and devcon, but you first have to remove the device in device manager to make the service switch to "STOPPED" afterwards. 
If I take `spl_start` and `zfs_start` back in it doesn't work in either cases, so search continues..

**Comment by jheuking** [comment]
just tested that with fastfat and cdfs and both hang in STOP_PENDING when I `sc stop fastfat` / `sc stop cdfs`, so they don't call unload either 😕

**Comment by jheuking** [comment]
that's it probably 
>your unload routine will not be called as long as you are registered as a
file system. You need to unregister before trying to unload the driver. To
do this write a tool which issues a private IOCTL which unregisters your
FSD. Then unload.

https://community.osr.com/discussion/34043/fsd-unregister-unload-questions

**Comment by jheuking** [comment]
Never mind 😉 regarding the uninstall, I would suggest to implement a console application (zfsinstaller maybe?) that does all the setup stuff for us. 
could be used like this 

```
zfsinstaller install [inf] [installFolder] (could default to something like %ProgramFiles%\ZFS)
zfsinstaller uninstall [inf] (could default to something like %ProgramFiles%\ZFS\ZFSin.inf)
```

or we add some options to our already existing tools, something like zfs install or zfs uninstall...?

**Comment by lundman** [comment]
Yeah either way would be fine by me, although I think it should probably live in `zpool` as it has fewer requirements to `zfs`. But if it was in `zpool` it can easily check things like `export pools` first.

**Comment by jheuking** [comment]
hm yeah you got a valid point... on the other hand, using a standalone installer has advantages if we want to setup the usermode applications as well. E.g. if we do `zpool install` it cannot move itself to a different location. 
Think it would be nice if we would create a \ProgramFiles\ZFS\ folder, which we add to the PATH environment variable, so that we can call our usermode applications anywhere.
But, as you said, some checks before unloading the driver are probably necessary, maybe we can do that in `zfs_unregister_fs`, if we need to call that anyway?

**Comment by lundman** [comment]
If a stand-alone program would be easier, it is pretty common to just system("zpool status"); to confirm pools are exported, so it isn't a show-stopper. If it was something you wanted to dig into, otherwise it goes on TODO for a later day :)

**Comment by jheuking** [comment]
already in progress 😜 would at least do everything that is needed to make the driver uninstallable... think we can add further functionality bit by bit if the basic installer works

**Comment by lundman** [comment]
yeah, perfect!
