### ISSUE TITLE
Panic: Stop Code: REFERENCE BY POINTER

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#61]
Steps to reproduce:
Import pool
Change directory to pool's "implicit dataset" (top directory)
Edit a file in VIM with a leftover from the previous session (i.e. .touch-files.sh.swp for file touch-files.sh)$ cat .touch-files.sh.swp
U3210#"! U¦[¦C¦¦@!dexterT430/cygdrive/d/touch-files.shutf-8
Using Cygwin, not sure if that changes anything.
See attached debug output.
[dbgview2018-09-15-4.txt](https://github.com/openzfsonwindows/ZFSin/files/2387473/dbgview2018-09-15-4.txt)

**Comment by michaeldexter** [comment]
REFERENCE BY POINTER is my most frequent panic.

Another for which I am missing debug output is: KMODE EXCEPTION NOT HANDLED

Though my testing is similar in all cases: Run a script that creates 2MiB files 100 times (generally successful) or edit a file in vi.

Repeated exports and imports of the pool have proven stable!

**Comment by lundman** [comment]
02bd32a29bdc414545dc63de02d0027e41acd194

Seems to fix 2 issues for me here, if you can try, grab the `ZFSin.sys` from www.lundman.net/ZFSin.sys

**Comment by michaeldexter** [comment]
[dbg-2018-09-18-2.txt](https://github.com/openzfsonwindows/ZFSin/files/2393915/dbg-2018-09-18-2.txt)

**Comment by michaeldexter** [comment]
Strangely, opening a file with vi that has .swo and .swp swap files consistently panics the system.

$ file .touch-files.sh.swo
.touch-files.sh.swo: Vim swap file, version 8.0, pid 3520, user dexter, host T430, file /cygdrive/d/touch-files.sh

dexter@T430 /cygdrive/d
$ file .touch-files.sh.swp
.touch-files.sh.swp: Vim swap file, version 8.0, pid 4208, user dexter, host T430, file /cygdrive/d/touch-files.sh, modified

**Comment by michaeldexter** [comment]
Initial testing results are encouraging! Good work!

**Comment by lundman** [comment]
d4569c7
