### ISSUE TITLE
Panic: Stop Code: KERNEL SECURITY CHECK FAILURE

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#62]
Steps to reproduce:
Import pool
Change directory to pool's "implicit dataset" (top directory)
Edit file in VIM
PANIC
[dbgview2018-09-15-6.txt](https://github.com/openzfsonwindows/ZFSin/files/2387519/dbgview2018-09-15-6.txt)

Using Cygwin, not sure if that changes anything.
See attached debug output.

**Comment by lundman** [comment]
d4569c7
