### ISSUE TITLE
Panic: Stop Code: KMODE EXCEPTION NOT HANDLED

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#63]
Import, generate data.
Click on Windows Explorer, BOOM
Not specifying the drive, though it is mapped to D:

See attached debug input
[dbg-2018-09-16-9.txt](https://github.com/openzfsonwindows/ZFSin/files/2387616/dbg-2018-09-16-9.txt)

LONG because of so much success.

Touching 10,000 files is reliable.

**Comment by jheuking** [comment]
the log file is missing ...

**Comment by michaeldexter** [comment]
Weird. Trying again. Maybe it choked on the length.
[dbg-2018-09-16-9.txt](https://github.com/openzfsonwindows/ZFSin/files/2389317/dbg-2018-09-16-9.txt)

**Comment by michaeldexter** [comment]
Eeek. 16MB. Creating a shorter one...
[chop.txt](https://github.com/openzfsonwindows/ZFSin/files/2389324/chop.txt)

**Comment by michaeldexter** [comment]
Still present. ZFS on Windows will handle quite a write load but switching to D: in Explorer will often cause the KMODE EXCEPTION NOT HANDLED panic.

**Comment by lundman** [comment]
Ok, when you say switching to D: in Explorer, you just click to get there? New Explorer, My Computer, D:  sort of thing?

**Comment by michaeldexter** [comment]
Sometimes simply opening my first Explorer window, sometimes when drilling up and down in D:

**Comment by lundman** [comment]
Ok, so browsing around I triggered:

```
SYSTEM_SERVICE_EXCEPTION (3b)
EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
ZFSin!ZFSCallbackAcquireForCreateSection+ed [c:\src\zfsin\zfsin\zfs\module\zfs\zfs_vnops_windows.c @ 5127]
```

It would seem that we are a little too eager to release a `vp` in CLEANUP sometimes. If they have called `ZFSCallbackAcquireForCreateSection()` which is the locking call, we should most likely hold an `iocount` on the vp, as we do in `zfs_AcquireForLazyWrite()`.  We should probably define the partner to it too, perhaps `PreReleaseForSectionSynchronization` or `PostReleaseForSectionSynchronization`.

Or possibly, we should acquire the `vp->FileHeader.Resource` in CLEANUP?

Either way, this is wrong right now :)

**Comment by lundman** [comment]
There may very well be more corner cases lingering, but hoping this commit will make it harder for you to crash

5662acd6b46ae50f536751fac1b957c11f6a47ff

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin/commit/5662acd6b46ae50f536751fac1b957c11f6a47ff

Create new ticket if it comes back.
