### ISSUE TITLE
Cygwin "touch" fails

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#64]
On the "implicit" (top of the pool) dataset:

dexter@T430 /cygdrive/d
$ touch foo
touch: setting times of 'foo': Invalid request code

dexter@T430 /cygdrive/d
$ touch ~/cyghome/foo

Attaching debug information.
[dbg-2018-09-17-1.txt](https://github.com/openzfsonwindows/ZFSin/files/2389293/dbg-2018-09-17-1.txt)

**Comment by michaeldexter** [comment]
Same result with Git BASH.

**Comment by lundman** [comment]
02bd32a29bdc414545dc63de02d0027e41acd194

**Comment by michaeldexter** [comment]
The /usr/bin/touch issue appears to be resolved! Great work!

**Comment by michaeldexter** [comment]
I can't help but notice that my write speed has increased from 1.5 MB/s to 1.7 MB/s!

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin/commit/02bd32a29bdc414545dc63de02d0027e41acd194
