### ISSUE TITLE
Panic: Stop code: SYSTEM SERVICE EXCEPTION (ZFSin.sys)

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#65]
Wrote 8 or so GB to the drive with repeated dd runs and then ran CrystalDiskMark default test, resulting in the panic. See attached debug information.
[20180918c.txt](https://github.com/openzfsonwindows/ZFSin/files/2394212/20180918c.txt)

**Comment by michaeldexter** [comment]
This will trigger with the system simply sitting idle after experiencing some load.

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin/commit/5662acd6b46ae50f536751fac1b957c11f6a47ff

**Comment by michaeldexter** [comment]
I fear this one is still lurking if high load is applied. I will keep increasing the stress I apply.
