### ISSUE TITLE
Panic: Stop code: UNEXPECTED KERNEL MODE TRAP (ZFSin.sys)

### ISSUE THREAD

**Issue by michaeldexter** [openzfsonwindows/ZFSin#66]
Following the SYSTEM SERVICE EXCEPTION panic, two attempts to import the pool result in this error.

See attached debug information.
[20180918d.txt](https://github.com/openzfsonwindows/ZFSin/files/2394225/20180918d.txt)

**Comment by michaeldexter** [comment]
zpool will import and scrub under FreeBSD 12.0-ALPHA5

**Comment by michaeldexter** [comment]
zpool failed to import twice. Succeeded with -N no mount and then could re-import with mount.

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/ZFSin/commit/5662acd6b46ae50f536751fac1b957c11f6a47ff
