### ISSUE TITLE
Fixing BSODs, etc. in ERAM

### ISSUE THREAD

**Issue by Zero3K** [openzfsonwindows/ZFSin#84]
It would be nice if you could try doing that. Its source code is available at https://github.com/Zero3K/ERAM.

**Comment by michaeldexter** [comment]
I am unable to determine from your ticket or the ERAM project page what this in fact does. I will personally consider it malicious until the tool is better understood.

**Comment by michaeldexter** [comment]
This appears to be an "Open Source RAM Disk". Could you please explain that on the project page and provide information about its usage?

**Comment by Zero3K** [comment]
I did the changes you requested. Let me know if they need improving or not.

**Comment by lundman** [comment]
Not sure what ERAM has to do with this project? Some parts look interesting though, but it isn't this/my project, so I am not going to work on ERAM.  I'm also not sure what changes you mean? I do not think I saw any changes from you here? Did you create this ticket in the wrong repo?

**Comment by Zero3K** [comment]
michaeldexter was wanting me to change the Readme in the repository that I linked to. I was letting him know that I did that.
