### ISSUE TITLE
spl_event_thread: LOWMEMORY EVENT 

### ISSUE THREAD

**Issue by jheuking** [openzfsonwindows/ZFSin#91]
When I run my tests with 1GB files, ZFS uses all of the available RAM and after that gets stuck. That means like 2,75GB.
The test includes file copy, replace, delete and such things..

**Comment by lundman** [comment]
I've been unable to test for memory-leaks since we did not free any vnodes until very recently. But we are at the point where we can start looking at memory usage, and making sure we stay under the limit.

**Comment by jheuking** [comment]
ah, the huge blksz gets set right there in zfs_vnop_lookup
https://github.com/openzfsonwindows/ZFSin/blob/e54d0af07ba267f30b124b360aa9598ec5f1355a/ZFSin/zfs/module/zfs/zfs_vnops_windows.c#L1062

**Comment by jheuking** [comment]
fixed b0799d3243ca75e563e29b0645d29b41b55e4365
