### ISSUE TITLE
Can not create Pool

### ISSUE THREAD

**Issue by zpoolfan** [openzfsonwindows/ZFSin#93]
Installation went fine, "zpool status" returns "no pools available"
Test area is a W10 VM with 2 vdisks where disk 1 = C: (and the system) and the 2nd i tried to mount.
So, wmic reports the expected "\\.\PHYSICALDRIVE0  VMware, VMware Virtual S SCSI Disk Device" for C: and "\\.\PHYSICALDRIVE1  VMware, VMware Virtual S SCSI Disk Device" intended for the pool.

Vmwaretools are installed btw.
"zpool create tank \\.\PHYSICALDRIVE1"   then results in
DeviceName said OK with '*'
DriveGeometry said OK
LayoutInfo said OK
DiskExtents said NG
cannot create 'tank': invalid argument for this pool operation"

**Comment by lundman** [comment]
It turns out that every shell handles "\" differently and needs to be escapes differently, so we added the shorthand "PHYSICALDRIVE" logic instead, so remove the "\" and try again.

**Comment by zpoolfan** [comment]
Hm. Did not use any ""; I just intended to highlight the entered string, maybe i caused a misunderstanding with that. I'm sorry for that.

Btw, I did that directly within Windows plain cmd.exe without any other shell. of course with admin rights on.
So, booting the Win VM, opening a cmd.exe (with admin rights), and entering

zpool create tank \.\PHYSICALDRIVE1

results in above error.
Also cleaning up the Vdisk with diskpart makes no difference.
The Vdisk itself is fine; Diskpart (or diskmgmt.msc) sees it and i can place regular NTFS volumes on it. No problem there.
Btw, I should state that it's German W10pro; maybe this could result in some sort of text parsing or decimal sign issue? Maybe, I should check with an english installation?

**Comment by jheuking** [comment]
just try zpool create tank PHYSICALDRIVE1, without any funky stuff in front of PHYSICALDRIVE

**Comment by JerryGan2** [comment]
zpool create tank PHYSICALDRIVE1
or
zpool create tank \??\PHYSICALDRIVE1

**Comment by zpoolfan** [comment]
Thanks very much for your help; i just installed the last debug binary and left aways the \??\ and it works. 
So, consider it as solved. :-)
Looking forward to experiment with it.
