### ISSUE TITLE
Partition based zpool is not imported

### ISSUE THREAD

**Issue by raindev** [openzfsonwindows/ZFSin#94]
I have a zpool residing on a partition of an external USB drive. The pool was created on Ubuntu 18.10 (`userobj_accounting` feature disabled), I can successfully import it with ZFS on macOS. When I try to import the zpool on Windows it fails with "no pool available to import". Below is the full output:

```
PS C:\WINDOWS\system32> zpool import -a
path '\\?\usbstor#disk&ven_toshiba&prod_external_usb_3.0&rev_5438#20170222008431f&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive1'
read partitions ok 7
    gpt 0: type 6c54e010 off 0x100000 len 0xc800000
    gpt 1: type 6c54e010 off 0xc900000 len 0x3ff8000000
    gpt 2: type 6c54e010 off 0x4004900000 len 0x8000000
    gpt 3: type 6c54e010 off 0x4014900000 len 0x3ff8000000
    gpt 4: type 6c54e010 off 0x800c900000 len 0x8000000
    gpt 5: type 6c54e010 off 0x801c900000 len 0x4000000000
    gpt 6: type 6c54e010 off 0xc01c900000 len 0x10000000000
asking libefi to read label
EFI read OK, max partitions 128
    part 0:  offset 800:    len 64000:    tag: c    name: ''
    part 5:  offset 400e4800:    len 20000000:    tag: 11    name: ''
    part 6:  offset 600e4800:    len 80000000:    tag: 18    name: ''
path '\\?\scsi#disk&ven_nvme&prod_samsung_ssd_970#5&2b537fae&0&000000#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}'
 and '\\?\PhysicalDrive0'
read partitions ok 5
    gpt 0: type 6c54e010 off 0x100000 len 0x20000000
    gpt 1: type 6c54e010 off 0x20100000 len 0x3a35300000
    gpt 2: type 6c54e010 off 0x3a55400000 len 0x1000000
    gpt 3: type 6c54e010 off 0x3a56400000 len 0x39fc035e00
    gpt 4: type 6c54e010 off 0x7452500000 len 0x1e600000
asking libefi to read label
EFI read OK, max partitions 128
    part 0:  offset 800:    len 100000:    tag: c    name: 'EFI System Partition'
    part 2:  offset 1d2aa000:    len 8000:    tag: 10    name: 'Microsoft reserved partition'
    part 3:  offset 1d2b2000:    len 1cfe01af:    tag: 11    name: 'Basic data partition'
Processing volume '\\?\Volume{0549f7ae-cbb0-4af7-9f64-3a23aef33950}'
Processing volume '\\?\Volume{327146c5-ced9-4129-bff6-5e78db0acc6b}'
Processing volume '\\?\Volume{314a8f86-f04a-d241-b93e-2115405c75dc}'
Processing volume '\\?\Volume{ff668337-d81f-4e90-9025-a45dcc775840}'
Processing volume '\\?\Volume{7c3c318b-91e7-f942-99fa-d1bc7c91d6b0}'
Processing volume '\\?\Volume{71dd626b-057e-11e9-9ac5-806e6f6e6963}'
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
zpool_open_func_win: enter
device '\\?\Volume{0549f7ae-cbb0-4af7-9f64-3a23aef33950}' filetype 1 0x3
device '\\?\Volume{314a8f86-f04a-d241-b93e-2115405c75dc}' filetype 1 0x3
device '\\?\Volume{314a8f86-f04a-d241-b93e-2115405c75dc}' filetype 1 0x3
device '\\?\Volume{327146c5-ced9-4129-bff6-5e78db0acc6b}' filetype 1 0x3
device '\\?\Volume{ff668337-d81f-4e90-9025-a45dcc775840}' filetype 1 0x3
device '\\?\Volume{71dd626b-057e-11e9-9ac5-806e6f6e6963}' filetype 1 0x3
device '\\?\Volume{71dd626b-057e-11e9-9ac5-806e6f6e6963}' filetype 1 0x3
device '\\?\Volume{7c3c318b-91e7-f942-99fa-d1bc7c91d6b0}' filetype 1 0x3
device '\\?\Volume{327146c5-ced9-4129-bff6-5e78db0acc6b}' filetype 1 0x3
device '\\?\Volume{ff668337-d81f-4e90-9025-a45dcc775840}' filetype 1 0x3
device '\\?\Volume{0549f7ae-cbb0-4af7-9f64-3a23aef33950}' filetype 1 0x3
device '\\?\Volume{7c3c318b-91e7-f942-99fa-d1bc7c91d6b0}' filetype 1 0x3
no pools available to import
```
The zpool is named `external` and is located on partition number 7 of PhysicalDrive1. Let me know if I could post some other useful details about the zpool/disk.

ZFS on Windows version is 0.14 Yuletime release.

**Comment by raindev** [comment]
Looking at #38 it seems that a possible culprit might be lack of a partition label mentioning "zfs", I shall try to add such a label.

In general, is it (relatively) safe to import an existing zpool at this point?* Does importing a zpool read-only make a difference?

*I understand that this is a very early experimental pre 1.0 software and you cannot promise anything about the data being intact.

**Comment by raindev** [comment]
After setting partition label to `zfs-external` I can import the zpool successfully.

**Comment by lundman** [comment]
Ah interesting - perhaps we should pay more attention to the GUID rather than the name of the partition, or both I suppose. 

Import read-only has not yet been implemented - and I have no lost any pools myself yet, but you'll have to decide yourself if it is worth the risk :)

**Comment by raindev** [comment]
I'm not sure how other implementations are doing discovery but I was able to import the same zpool created on Ubuntu without partlabel from macOS successfully.

Read-only import - that makes sense: I ended up with a drive containing empty directories when mounted a zpool read-only. Also export command got stuck (I also tried remounting one of the datasets read-write in the meantime).

The promise of having a ZFS-formatted drive available to Linux/macOS/Windows/FreeBSD is too compelling to not try :)
Thank you for your work on the project!

**Comment by raindev** [comment]
It seems the dataset directories where empty not just because I've tried to import the zpool read-only. Now importing the pool read-write I get the same results. The pool is imported successfully, I can list datasets but their directories are empty. Interestingly `mounted` property is only `yes` for one of the datasets and for the zpool itself:

```
C:\WINDOWS\system32>zfs get mounted
NAME                    PROPERTY  VALUE    SOURCE
external                mounted   yes      -
external/archive        mounted   yes      -
external/important      mounted   no       -
external/media          mounted   no       -
external/ubuntu-backup  mounted   no       -
```
