### ISSUE TITLE
Expanding ZIP archive using WinRAR results in weird behaviour

### ISSUE THREAD

**Issue by vmlemon** [openzfsonwindows/ZFSin#96]
Using Windows 10 Pro Build 16299.rs3_release.170928-15434, WinRAR 5.61, OpenZFS 0.14.

As an experiment, I created a 20GB VHD (on my laptop's internal eMMC drive, in an NTFS partition), mounted it with Disk Management, and created a pool using:

C:\Windows\system32> wmic diskdrive list brief
Caption                 DeviceID            Model                   Partitions  Size
Microsoft Virtual Disk  \\.\PHYSICALDRIVE2  Microsoft Virtual Disk  0           21467980800
SanDisk DF4032          \\.\PHYSICALDRIVE0  SanDisk DF4032          3           31264289280
SDXC Card               \\.\PHYSICALDRIVE1  SDXC Card               1           128042933760

C:\Windows\system32>zpool create CompDisk PHYSICALDRIVE2
Expanded path to '\\?\PHYSICALDRIVE2'
DeviceName said OK with '*'
DriveGeometry said OK
LayoutInfo said OK
DiskExtents said NG

C:\Windows\system32>zpool list
NAME       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
CompDisk  19.5G    78K  19.5G        -         -     0%     0%  1.00x  ONLINE  -

C:\Windows\system32>zfs set dedup=on CompDisk

C:\Windows\system32>zfs set compress=on CompDisk

C:\Windows\system32>zpool list
NAME       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
CompDisk  19.5G   631K  19.5G        -         -     0%     0%  1.00x  ONLINE  -

The pool itself was created fine, and I was able to use Windows Explorer, to add files to the root of the volume, and verified their persistence, by exporting, and reimporting the pool, to satisfaction.

Afterwards, I tried to download a Google Takeout ZIP archive (containing Location History data, which consists of extremely-redundant data, well-suited for ZFS compression, and deduplication, once unpacked), using Chrome, to the root of the volume - which worked fine, given the streaming writing + later rename style process, and the later writing of the Zone.Identifier stream. 

However, when trying to unpack the archive onto the root of the volume, using WinRAR - despite it claiming that everything had been read from the archive, and extracted successfully (which seems to invoke a file copying/move process, after dumping the payload into a temporary directory), only a single file was actually present, from the archive (the "index.html" file), which was renamed with the name of the directory that WinRAR would have created (which matches the archive name - i.e. "takeout-20190107T023445Z-001"), and the remaining data wasn't actually written into either a directory, or the root of the volume.

I'm unsure of the best way of debugging the I/O involved, but I'm pretty sure that this isn't the intended outcome (on both NTFS, and an inserted SD card, formatted using the WinBTRFS driver, I receive a new directory, with contents corresponding to those from the archive).

**Comment by lundman** [comment]
Neat - sounds like maybe unrar does something unusual - I will give it a go and see if I can replicate.

**Comment by lundman** [comment]
I had success with:
e00dcdb69dc7f01787fdf2631fbe841a36c2eeb4

**Comment by vmlemon** [comment]
Thanks for looking into this, and for the quick fix! This seems to work properly, for me, using the latest "Tungsten" debug release, on the same build of Windows.
