### ISSUE TITLE
Sandboxie can't run programs on ZFS

### ISSUE THREAD

**Issue by vmlemon** [openzfsonwindows/ZFSin#99]
When trying to run an application using "Sandboxie", on a ZFS volume (with the sandbox container directory set to a directory on the ZFS volume), the Sandboxie Control tool will bail out, with the error described at https://www.sandboxie.com/SBIE1211, and the application will not run. 

(As a sidenote - the first time that I attempted this, I received a BSOD, but I wasn't able to reproduce it, this time)

It seems that attempting to create the sandbox data directory fails, and the permissions of the directory containing the executable to be run inside the sandbox are quietly changed, so that it cannot be opened from Windows Explorer, by a standard user account (Explorer reports "Location is not accessible: D:\DiskMon is not accessible. Access denied"), the directory is marked as being of 0-size, and the ACLs are set in a manner that the owner information cannot be viewed, without Administrator privileges (or at all, with "icacls", from an Administrator cmd.exe session: 

"C:\Windows\system32>icacls D:\DiskMon
D:\DiskMon: Access is denied.
Successfully processed 0 files; Failed processing 1 files", until permission is granted to the current user, with Windows Explorer).

The ACLs that get set seem to look like:

C:\Windows\system32>icacls D:\DiskMon
D:\DiskMon BUILTIN\Administrators:(F)
           NT AUTHORITY\SYSTEM:(F)
           NT AUTHORITY\LogonSessionId_0_319642:(RX)

Successfully processed 1 files; Failed processing 0 files

-

Unsure if it makes a difference, but the ZPool is configured to use deduplication, and compression.

Using Windows 10 Pro Build 16299.rs3_release.170928-15434, WinRAR 5.61, OpenZFS 0.15.

**Comment by lundman** [comment]
ACL, XATTR and Streams are features I have not yet implemented, not even stub functions - so it's a bit random as to what would happen. Although I advertise NOT supporting them so it looks like it ignores that (but that is pretty common with users of filesystems).

One temporary fix could be to implement functions that just return "sure thing" but does nothing. Eventually I will get to those features though.

**Comment by lundman** [comment]
I tested Sandboxie with the branch `Streams` today, after `Set Container Folder` was set to ZFS, I ran Notepad.exe without issues - or at least it seemed to work to me.

**Comment by vmlemon** [comment]
Thanks for looking at this - it seems to get further, with the latest release (0.16), although when running Chrome, the Sandboxie log is spammed with:

SBIE2101 Object name not found: \BaseNamedObjects\IGFXKMDNotifyBatchBuffersComplete, error OpenEvent (C0000022) access=001F0003 initialized=1
SBIE2101 Object name not found: \BaseNamedObjects\IGFXKMDNotifyBatchBuffersComplete, error OpenEvent (C0000022) access=001F0003 initialized=1
SBIE2101 Object name not found: \BaseNamedObjects\IGFXKMDNotifyBatchBuffersComplete, error OpenEvent (C0000022) access=001F0003 initialized=1

Thankfully, that seems to be more of an issue in Sandboxie itself, and Google Chrome seems to start up fine, without a BSOD, or otherwise trashing my file system...

Playing with 0.15, I managed to get to a state where I needed to use a FreeBSD VM, to import the pool, and run a scrub, and dmesg was reporting some fun errors:

![gamesoft on freebsd](https://user-images.githubusercontent.com/35642/53490805-87d18b00-3a8c-11e9-8b42-969036987efd.PNG)

Thankfully, I don't seem to have lost any data, from that adventure.

As a side note, it doesn't fix setting a ZFS volume as a default "save location" for Windows Store apps, or as a location for maps (but, really, I should report that, as its own bug):

![image](https://user-images.githubusercontent.com/35642/53490912-d0894400-3a8c-11e9-8b62-4b06832107c6.png)

**Comment by vmlemon** [comment]
Had a play, some more, and tried loading a few pages in Chrome... 

I managed to get a BSOD (System Thread Exception Not Handled), before trying to perform a search, using the address bar - but, Windows doesn't seem to be writing out the MiniDumps, so I can't see what the problem is; and, after rebooting, I have to force a pool import, since it claims to be in use, by another system. 

When I actually try to do the forced import, I suddenly get an "Unexpected Kernel Mode Trap" BSOD, which always stays at "0% complete", and I have to manually switch off my PC. (I haven't got a large enough internal drive, for the development environment, so I'm bravely testing using bare hardware, and  VHD files, on an external USB HDD).

**Comment by vmlemon** [comment]
Managed to get a DbgView log, from before it goes off the rails - sadly, it doesn't say anything informative, after "00003264	172.49069214	probing object 0 offset 1000000 level 2 of 2", which is the last gasp, before the SYSTEM_THREAD_EXCEPTION_NOT_HANDLED.

Annoyingly, I can't get MiniDumps, on this machine; and, the latest release doesn't seem to be able to create ZPools, anymore, for me. :(

[dbgview.log](https://github.com/openzfsonwindows/ZFSin/files/2910470/dbgview.log)

**Comment by vmlemon** [comment]
Curiously, it looks like I'm able to start the Visual Studio online installer, from within a sandbox, which gets as far as letting me select components to install, and even beginning to download packages, after playing with drive letter substitution (since the broken installer wants to dump shared components onto a non-existent E:\ drive, for some reason), although I seem to eventually get a BSOD, for some reason.

**Comment by vmlemon** [comment]
It does, however, let you use Microsoft Network Monitor 3.4 (which doesn't ordinarily allow setting the temporary storage location, to what it deems to be a "removable disk"), to do network captures, within a sandbox, though; and, I also tried CygWin's installer, which just refused to launch, since it claimed that it wasn't a valid executable (but, that's probably a Sandboxie bug).

**Comment by vmlemon** [comment]
On another note, the recent changes **do** mean that you can install the 64-bit version of CygWin, for the first time (with Sandboxie disabled), without it complaining about free space - although, the resulting installation doesn't seem to work properly (BASH conks out with "Failed to run '/bin/bash': No such file or directory
/bin/bash: Exit 126", and some files seem to be missing).

**Comment by vmlemon** [comment]
Amazingly, "Location History Visualizer Pro 1.5.2" (a Chromium Embedded Framework-based application), from https://locationhistoryvisualizer.com/ will actually install, and run, on ZFS - which doesn't even work, on WinBTRFS, as of OpenZFS 0.16...

Getting a few APC_INDEX_MISMATCH BSODs, with various things, but I'm amazed by what does work, compared to 0.15, though.

**Comment by lundman** [comment]
If you can find problems easily repeatable that I can run and trigger, it would help. As for no minidump, you have checked the things in here: https://answers.microsoft.com/en-us/windows/forum/windows_10-update/bsod-finding-and-fixing-them/1939df35-283f-4830-a4dd-e95ee5d8669d

The debuglog does not contain much now - it is way too slow. We now print into the circular buffer, that you can save from debugger, or windbb after loading minidump.

```
 *	get address of cbuf buffer:
 *		dt ZFSin!cbuf --> copy shown address
 *
 *	write memory to file
 *		.writemem [filepath] [cbuf address] L[Length as hex]
 *	e.g. .writemem C:\src\cbuf.txt 0xffff870d`d2000000 L100000
 *
```

**Comment by vmlemon** [comment]
No worries. 

I ended up uninstalling almost everything on my system (seems that I had a debug version, and a release version of ZFS drivers, but it didn't seem to make much of a difference), in a vague hope of trying to upgrade to a newer version of Windows 10 (the set-up files, and the existing Windows version alone take up almost all of the internal eMMC, so I can't free the remaining 2GB, that the installer wants!), but I managed to craft a small disk image, that triggers the APC_INDEX_MISMATCH BSOD, and, it seems, after an eternal delay, I managed to obtain a tiny kernel dump file...

[030119-14828-01.zip](https://github.com/openzfsonwindows/ZFSin/files/2919052/030119-14828-01.zip)

Using Chrome Version 72.0.3626.119 (Official Build) (64-bit), a small (dynamically expanding, up to 80MB, but only ~66MB used by the physical file) VHD containing a ZPool created using FreeBSD 12.0 (with deduplication/compression enabled, and a few snapshots, created during several attempts at running Chrome, in a sandbox - it hangs, repeatedly, presumably due to lacking disk space), and Windows 10 Pro build 16299.rs3_release.170928-1534.

[ChromeDisk.zip](https://github.com/openzfsonwindows/ZFSin/files/2919065/ChromeDisk.zip)

**Comment by vmlemon** [comment]
With the 20190307 build, Internet Explorer 11 can now run in a sandbox, without causing a nearly-instant BSOD; and the latest version of CygWin (64-bit) can fully install, and run (both in a sandbox, and outside of a sandbox), after a minor change to cygwin64/cygwin.bat (replacing `bash --login -i`, with `bash.exe --login -i`, since the batch file interpreter fails to find the executable, in the path, without the extension), without a bunch of missing files, that cause the installer's finalisation scripts to bail out.

Chrome won't launch, at all, in a sandbox, now - but, that's still kinder to a working file system, than producing a BSOD, not so long, after launch, and unceremoniously toasting things, to the point where it's necessary to boot into FreeBSD, to run the scrubbing tool, in order to roll back to a slightly-older transaction, I guess...

**Comment by lundman** [comment]
I believe the initial issue was fixed, please open new issues if there are further Sandboxie issues
